<span style="color: #FFC107; font-size: 22px;">Referências</span>

1. [Documentação do Numpy](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

<span style="color: #FFC107; font-size: 22px;">Importação das bibliotecas</span>

In [1]:
import numpy as np
import time

<span style="color: #FFC107; font-size: 22px;">**np.array()**</span> <br>

<span style="color: #FFC107; font-size: 18px;">No Numpy, todos os elementos de um `array` são do mesmo tipo.</span>

<span style="color: #FFC107; font-size: 18px;">Caso inicialmente eles sejam de tipos diferentes, o numpy altera para um formato mais genérico.</span>

In [5]:
# Definindo os elementos da lista
lista_elementos = [24, "Bom dia", 3.7]

# Percorrendo todos os elementos do array e apresentando o tipo do elemento
for elemento in lista_elementos: print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos do array
np_lista = np.array(lista_elementos)

# Percorrendo todos os elementos do array e apresentando o tipo do elemento
for elemento in np_lista: print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos da lista
lista_elementos = [24, 2.5 , 9, 3.7, True, False]

# Percorrendo todos os elementos do array e apresentando o tipo do elemento
for elemento in lista_elementos: print(type(elemento))
    
# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos do array
np_lista = np.array(lista_elementos)

# Percorrendo todos os elementos do array e apresentando o tipo do elemento
for elemento in np_lista: print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

<class 'int'>
<class 'float'>
<class 'int'>
<class 'float'>
<class 'bool'>
<class 'bool'>

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


![Como funciona um array numpy](images_markdown\numpy_image.png)

<span style="color: #FFC107; font-size: 18px;">Na lista não é possível somar um número qualquer de forma direta.</span>

<span style="color: #FFC107; font-size: 18px;">Já em um array do Numpy isso é possível.</span>

In [42]:
# Cria uma lista de números
lista_numeros = [1, 2, 3, 4]
print("lista_numeros = ", lista_numeros)

# Acrescenta o número 1 a lista
lista_numeros = lista_numeros + [1]

# Apresenta a lista de números com o acréscimo do número 2
print("lista_numeros + [1] = ", lista_numeros, '\n')

#=====================================================================

# Cria um array
np_numeros = np.array(lista_numeros)
print("np_numeros = ", np_numeros)

# Soma o número 1 ao array
np_numeros = np_numeros + 1

# Apresenta a soma do número 1 ao array
print("np_numeros + 1 = ", np_numeros)

lista_numeros =  [1, 2, 3, 4]
lista_numeros + [1] =  [1, 2, 3, 4, 1] 

np_numeros =  [1 2 3 4 1]
np_numeros + 1 =  [2 3 4 5 2]


<span style="color: #FFC107; font-size: 18px;">O tempo de processamento de um variável Numpy é mais rápido.</span>

In [ ]:
# Lista com números de 1 à 10.000.000
lista = list(range(1, 20_000_000))

# Tempo inicial
inicio_lista = time.time()

# Calcula todos os elementos da lista
soma_lista = sum(lista)

# Tempo final
fim_lista = time.time()

# Calcula o tempo necessário para calcular os elementos da lista
duracao_lista = fim_lista - inicio_lista

# Apresenta a duração para somar todos os números da lista
print(f'O tempo total para somar os elementos da lista foi de: {duracao_lista:.7f} segundos')

#================================================================================================

# Array com números de 1 à 10.000.000
array = np.array(range(1, 20_000_000))

# Tempo inicial
inicio_np = time.time()

# Calcula todos os elementos da lista
soma_lista = np.sum(array)

# Tempo final
fim_np = time.time()

# Calcula o tempo necessário para calcular os elementos da lista
duracao_np = fim_np - inicio_np

# Apresenta a duração para somar todos os números do array
print(f'O tempo total para somar os elementos do array foi de: {duracao_np:.7f} segundos')

#================================================================================================

if duracao_np != 00:
    print(f'O array do Nympy é {(duracao_lista / duracao_np):.2f} vezes mais rápido.')

O tempo total para somar os elementos da lista foi de: 0.4567010 segundos
O tempo total para somar os elementos do array foi de: 0.0000000 segundos


<span style="color: #FFC107; font-size: 22px;">**.dtype**</span> <br>
<span style="color: #FFC107; font-size: 22px;">**.itemsize**</span> <br>
<span style="color: #FFC107; font-size: 22px;">**.size**</span> <br>
<span style="color: #FFC107; font-size: 22px;">**.ndim**</span> <br>
<span style="color: #FFC107; font-size: 22px;">**.shape**</span> <br>

In [43]:
# Definindo os elementos do array como float
array_float = np.array([1, 2, 3, 4, 5, 6], dtype = float)
print(array_float, '\n')

# Definindo os elementos do array como complex
array_compex = np.array([[1 + 3j, 2 + 1j, 3], [4, 5, 6]], dtype = complex)
print(array_compex, '\n')

# definindo os elementos do array como int32
array_int32 = np.array([1, 2, 3, 4, 5, 6], dtype = np.int32)
print(array_int32, '\n')

#=====================================================================================

# Apresenta o tipo de dado
print(f"{array_int32.dtype = }")

# Apresenta o tamanho em bytes de cada elemento
print(f"{array_int32.itemsize = }")

# Apresenta a quantidade de elementos
print(f"{array_compex.size = }")

# Apresenta a quantidade de dimensões
print(f"{array_compex.ndim = }")

# Apresenta as dimensões
print(f"{array_compex.shape = }")

[1. 2. 3. 4. 5. 6.] 

[[1.+3.j 2.+1.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]] 

[1 2 3 4 5 6] 

array_int32.dtype = dtype('int32')
array_int32.itemsize = 4
array_compex.size = 6
array_compex.ndim = 2
array_compex.shape = (2, 3)


In [58]:
# 1 dimensão
e = np.array([7,5,3,16,39])
print(e, '\n')

# 2 dimensões
f = np.array([(6,4,2),
              (3,8,1)])

print(f, '\n')

# 3 dimensões como tupla
g = np.array([(52,63,74),
              (96,2,15),
              (28,13,47)])

print(g, '\n')

# 3 dimensões como lista
g = np.array([[52,63,74], 
              [96,2,15], 
              [28,13,47]])
print(g, '\n')

h = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(h)

[ 7  5  3 16 39] 

[[6 4 2]
 [3 8 1]] 

[[52 63 74]
 [96  2 15]
 [28 13 47]] 

[[52 63 74]
 [96  2 15]
 [28 13 47]] 

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [ ]:
M1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{M1 = }') # imprime matriz
print(f'{M1[1, 2] = }') # imprime elemento com índices (1,2)
print(f'{M1[1, :] = }') # imprime linha de índice 1
print(f'{M1[1] = }') # mesmo que o de cima: imprime linha 1
print(f'{M1[:, 0] = }') # imprime coluna de índice 0
print(f'{M1[..., 0] = }') # mesmo que anterior: imprime coluna 0
print(f'{M1[1:, 1:] = }') # imprime submatriz

M1 = array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])
M1[1, 2] = 6
M1[1, :] = array([4, 5, 6])
M1[1] = array([4, 5, 6])
M1[:, 0] = array([1, 4, 7])
M1[..., 0] = array([1, 4, 7])
M1[1:, 1:] = array([[5, 6],
       [8, 9]])


<span style="color: #FFC107; font-size: 22px;">**np.sum()**</span> <br>

In [83]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Soma os elementos do array
soma_vetor = np.sum(vetor)
print('Soma: ', soma_vetor)

# Soma os elementos do array
soma_vetor = vetor.sum()
print('Soma: ', soma_vetor, '\n', '=' * 50)

print('Outro array:')
h = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print(h, '\n', '=' * 50)

# Soma os elementos de cada dimensão
soma_r_linha = h.sum(axis = 0)
print('Soma os elementos de cada dimensão: \n', soma_r_linha, '\n')

# Soma os elementos de cada linha

soma_r_coluna = h.sum(axis = 1)
print("Soma os elementos de cada coluna: \n", soma_r_coluna, '\n')

# Soma os elementos de cada linha
soma_r_coluna = h.sum(axis = 2)
print("Soma os elementos de cada linha: \n", soma_r_coluna)

Array:  [ 9  1 22  3 20 21 18]
Soma:  94
Soma:  94 
Outro array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]] 
Soma os elementos de cada dimensão: 
 [[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]] 

Soma os elementos de cada coluna: 
 [[15 18 21 24]
 [51 54 57 60]] 

Soma os elementos de cada linha: 
 [[10 26 42]
 [58 74 90]]


In [98]:
import numpy as np

# Exemplo 1: Soma de todos os elementos do array
array = np.array([[1, 2, 3], 
                  [4, 5, 6]])
soma_total = np.sum(array)
print("Soma total:", soma_total)

# Exemplo 2: Soma ao longo das linhas (axis=1)
soma_linhas = np.sum(array, axis=1)
print("Soma ao longo das linhas:", soma_linhas)

# Exemplo 3: Soma ao longo das colunas (axis=0)
soma_colunas = np.sum(array, axis=0)
print("Soma ao longo das colunas:", soma_colunas)

# Exemplo 4: Soma com dtype especificado
soma_dtype = np.sum(array, dtype=np.float64)
print("Soma com dtype especificado:", soma_dtype)

# Exemplo 5: Soma com keepdims=True
soma_keepdims = np.sum(array, axis=1, keepdims=True)
print("Soma com keepdims=True:", soma_keepdims)

Soma total: 21
Soma ao longo das linhas: [ 6 15]
Soma ao longo das colunas: [5 7 9]
Soma com dtype especificado: 21.0
Soma com keepdims=True: [[ 6]
 [15]]


In [114]:
import numpy as np

array = np.array([[1, 2, 3], 
                  [4, 5, 6]])

print(array, '\n')

#==========================================================================

# Soma ao longo do eixo 1 (linhas) sem keepdims
soma_sem_keepdims = np.sum(array, axis=1)
print("Soma sem keepdims: \n", soma_sem_keepdims, '\n')
print("Shape sem keepdims:", soma_sem_keepdims.shape, '\n', '=' * 50)

# Soma ao longo do eixo 1 (linhas) com keepdims=True
soma_keepdims = np.sum(array, axis=1, keepdims=True)
print("Soma com keepdims=True: \n", soma_keepdims)
print("Shape com keepdims:", soma_keepdims.shape, '\n', '=' * 50)

#==========================================================================

# Soma ao longo do eixo 1 (linhas) sem keepdims
soma_sem_keepdims = np.sum(array, axis=0)
print("Soma sem keepdims:", soma_sem_keepdims)
print("Shape sem keepdims:", soma_sem_keepdims.shape, '\n', '=' * 50)

# Soma ao longo do eixo 1 (linhas) com keepdims=True
soma_keepdims = np.sum(array, axis=0, keepdims=True)
print("Soma com keepdims=True: \n", soma_keepdims)
print("Shape com keepdims:", soma_keepdims.shape)

[[1 2 3]
 [4 5 6]] 

Soma sem keepdims: 
 [ 6 15] 

Shape sem keepdims: (2,) 
Soma com keepdims=True: 
 [[ 6]
 [15]]
Shape com keepdims: (2, 1) 
Soma sem keepdims: [5 7 9]
Shape sem keepdims: (3,) 
Soma com keepdims=True: 
 [[5 7 9]]
Shape com keepdims: (1, 3)


<span style="color: #FFC107; font-size: 22px;">**np.mean()**</span> <br>

In [94]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Faz a média dos elementos do array
media_vetor = np.mean(vetor)
print('Média: ', media_vetor)

# Faz a média dos elementos do array
media_vetor = vetor.mean()
print('Média: ', media_vetor, '\n')

# Definição do array
vetor = np.array([
                [9, 1, 22, 3, 20, 21, 18], 
                [1, 1, 1, 1, 1, 1, 1]])

print('Array: \n', vetor, '\n')

# Faz a média dos elementos do array
media_vetor = np.mean(vetor)
print('Média de todos os elementos: ', media_vetor)

# Faz a média de todos os elementos do array
media_vetor = vetor.mean()
print('Média de todos os elementos: ', media_vetor)

# Faz a média de todos os elementos do array
media_vetor = vetor.mean(axis = 1)
print('Média de cada linha: ', media_vetor)

# Faz a média de todos os elementos do array
media_vetor = vetor.mean(axis = 0)
print('Média de cada coluna: ', media_vetor)

Array:  [ 9  1 22  3 20 21 18]
Média:  13.428571428571429
Média:  13.428571428571429 

Array: 
 [[ 9  1 22  3 20 21 18]
 [ 1  1  1  1  1  1  1]] 

Média de todos os elementos:  7.214285714285714
Média de todos os elementos:  7.214285714285714
Média de cada linha:  [13.42857143  1.        ]
Média de cada coluna:  [ 5.   1.  11.5  2.  10.5 11.   9.5]


<span style="color: #FFC107; font-size: 22px;">**np.max()**</span> <br>

In [13]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Retorna o valor máximo do array
maximo_vetor = np.max(vetor)
print('Valor máximo: ', maximo_vetor)

# Retorna o valor máximo do array
maximo_vetor = vetor.max()
print('Valor máximo: ', maximo_vetor)

Array:  [ 9  1 22  3 20 21 18]
Valor máximo:  22
Valor máximo:  22


<span style="color: #FFC107; font-size: 22px;">**np.min()**</span>

In [14]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Retorna o valor mínimo do array
minimo_vetor = np.min(vetor)
print('Valor mínimo: ', minimo_vetor)

# Retorna o valor mínimo do array
minimo_vetor = vetor.min()
print('Valor mínimo: ', minimo_vetor)

Array:  [ 9  1 22  3 20 21 18]
Valor mínimo:  1
Valor mínimo:  1


<span style="color: #FFC107; font-size: 22px;">**np.sort()**</span>

<span style="color: #FFC107; font-size: 18px;">Ordena os elementos</span>

In [37]:
# Array unidimensional
array = np.array([3, 1, 5, 2, 4])

# Ordenando o array
array_ordenado = np.sort(array)

# Apresenta os arrays
print("Array original:", array)
print("Array ordenado:", array_ordenado, '\n')

#==============================================================================

# Array unidimensional
array = np.array(["Hoje", "amanhã", "Bom dia", "bom dia"])

# Ordenando o array
array_ordenado = np.sort(array)

# Apresenta os arrays
print("Array original:", array)
print("Array ordenado:", array_ordenado)

Array original: [3 1 5 2 4]
Array ordenado: [1 2 3 4 5] 

Array original: ['Hoje' 'amanhã' 'Bom dia' 'bom dia']
Array ordenado: ['Bom dia' 'Hoje' 'amanhã' 'bom dia']


In [35]:
# Array bidimensional
array = np.array([[3, 1, 5], [2, 4, 6], [7, 0, 9]])

# Ordenando cada linha do array
array_ordenado = np.sort(array, axis=1)

# Apresenta os arrays
print("Array original:\n", array, '\n')
print("Array ordenado por linha:\n", array_ordenado)

Array original:
 [[3 1 5]
 [2 4 6]
 [7 0 9]] 

Array ordenado por linha:
 [[1 3 5]
 [2 4 6]
 [0 7 9]]


In [34]:
# Array bidimensional
array = np.array([[3, 1, 5], [2, 4, 6], [7, 0, 9]])

# Ordenando cada coluna do array
array_ordenado = np.sort(array, axis=0)

# Apresenta os arrays
print("Array original:\n", array, '\n')
print("Array ordenado por coluna:\n", array_ordenado)

Array original:
 [[3 1 5]
 [2 4 6]
 [7 0 9]] 

Array ordenado por coluna:
 [[2 0 5]
 [3 1 6]
 [7 4 9]]


<span style="color: #FFC107; font-size: 22px;">**np.dot()**</span>

<span style="color: #FFC107; font-size: 18px;">Calcula o produto escalar de duas matrizes</span>

In [38]:
# Vetor que representa a quantidade de itens vendidos
quantidade = np.array([10, 2, 6, 9])

# Vetor que representa o preço unitário de cada item
preco_unitario = np.array([2, 1, 2, 2])

# Calcula o ganho de cada item
preco_quantidade = quantidade * preco_unitario

# Calcula o ganho total
soma_preco_quantidade = np.sum(preco_quantidade)

# Apresenta o ganho total
print(soma_preco_quantidade)

#=========================================================================================

# Calcula o produto escalar de dois vetores
soma_preco_quantidade = np.dot(quantidade, preco_unitario)

# Apresenta o ganho total
print(soma_preco_quantidade)

52
52


In [44]:
# Duas matrizes
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

# Produto de matrizes
produto_matrizes = np.dot(matriz1, matriz2)

# Apresenta as matrizes
print('Matriz 1:\n', matriz1, '\n')
print('Matriz 2:\n', matriz2, '\n')
print("Produto das matrizes:\n", produto_matrizes)

Matriz 1:
 [[1 2]
 [3 4]] 

Matriz 2:
 [[5 6]
 [7 8]] 

Produto das matrizes:
 [[19 22]
 [43 50]]


In [96]:
# Cria uma instância da classe 'default_rng()'
rng = np.random.default_rng()

# Gera um número aleatório e flutuante entre 0 e 1
numero_aleatorio_1 = rng.random()
print(numero_aleatorio_1, '\n')

# Gera 5 números aleatórios e flutuantes entre 0 e 100
numero_aleatorio_2 = rng.random(5) * 100
print(numero_aleatorio_2, '\n')

# Gera 20 números aleatórios inteiros entre 1 e 7
numero_aleatorio_3 = rng.integers(low = 1, high = 101, size = 20)
print(numero_aleatorio_3, '\n')

0.2638778466646875 

[87.18689035 38.82067778 17.51187463 15.80738718 20.43146287] 

[43 33  2 53 77 15 47 79 10 60 53 37 27 67 90  3 91 37 77 52] 



In [117]:
# Cria uma instância da classe 'default_rng()'
# Qualquer pessoa que usar a mesma 'seed' que esta, terá os mesmos resultados
rng = np.random.default_rng(seed = 42)

# Gera um número aleatório e flutuante entre 0 e 1
numero_aleatorio_1 = rng.random()
print(numero_aleatorio_1, '\n')

# Gera 5 números aleatórios e flutuantes entre 0 e 100
numero_aleatorio_2 = rng.random(5) * 100
print(numero_aleatorio_2, '\n')

# Gera 20 números aleatórios inteiros entre 1 e 7
numero_aleatorio_3 = rng.integers(low = 1, high = 101, size = 20)
print(numero_aleatorio_3, '\n')

# Apresenta a posição do maior elemento do array
posicao_max = np.argmax(numero_aleatorio_3)
print('O maior elemento está na posição: ', posicao_max, '\n')

# Apresenta a posição do menor elemento do array
posicao_min = np.argmin(numero_aleatorio_3)
print('O menor elemento está na posição: ', posicao_min)

0.7739560485559633 

[43.88784398 85.85979199 69.73680291  9.41773479 97.56223516] 

[74 77 72 79 52 13 84 46 51 38 19 93 79 65 41 83 55 45 46 23] 

O maior elemento está na posição:  11 

O menor elemento está na posição:  5


In [137]:
numero_aleatorio_4 = rng.integers(low = 100, high = 501, size = 100)
print(numero_aleatorio_4, '\n')

mediana = np.median(numero_aleatorio_4)
print('Mediana: ', mediana, '\n')

n_percentil = 1
percentil = np.percentile(numero_aleatorio_4, n_percentil)
print(f'{n_percentil}% dos elementos são menores ou iguais à: ', percentil, '\n')

desvio_padrao = np.std(numero_aleatorio_4)
print('Desvio padrão: ', desvio_padrao, '\n')

variancia = np.var(numero_aleatorio_4)
print('Variância: ', variancia)

[257 421 253 119 464 194 140 349 193 444 277 101 481 306 205 371 312 111
 404 260 380 459 344 369 202 195 266 441 310 239 412 442 461 219 384 336
 280 259 145 210 320 455 447 175 372 134 370 237 280 387 270 423 313 500
 355 218 410 263 314 154 147 330 174 500 443 381 394 338 124 257 298 467
 188 299 237 153 141 246 133 126 240 180 322 107 221 281 486 354 453 237
 280 268 455 484 485 401 301 316 493 214] 

Mediana:  300.0 

1% dos elementos são menores ou iguais à:  106.94 

Desvio padrão:  112.5178403632064 

Variância:  12660.2644


In [57]:
rng = np.random.default_rng()

numero_aleatorio_4 = rng.integers(low = 100, high = 200, size = (3, 5))
print(numero_aleatorio_4, '\n')

[[136 163 154 143 104]
 [128 160 141 106 142]
 [131 178 133 126 159]] 



In [65]:
rng = np.random.default_rng()

numero_aleatorio_4 = rng.integers(low = 1, high = 101, size = (3, 5, 4))
print(numero_aleatorio_4, '\n')

[[[95  9 46 94]
  [95  6 67 22]
  [14 85 94 40]
  [ 6 24 41 59]
  [74 86 31 86]]

 [[ 4 81 12 57]
  [61 63 22 89]
  [18 35 49 59]
  [55 37 66 73]
  [98 48  6 28]]

 [[73 92 34  6]
  [14 28 95 28]
  [10 52 82 65]
  [82 77 33 31]
  [97 14 71 45]]] 



<span style="color: #FFC107; font-size: 22px;">**np.where()**</span> <br>

In [24]:
x = np.random.randint(1, 7, 10)
print(x)

x[np.where(x > 5)]

np.where(x > 5)

[1 5 6 6 4 5 2 5 5 4]


(array([2, 3], dtype=int64),)

In [25]:
x > 5

array([False, False,  True,  True, False, False, False, False, False,
       False])

In [37]:
# Define uma seed para valores aleatórios
aleatorio = np.random.default_rng(seed = 42)

# Define um conjunto de valores aleatórios
salarios = aleatorio.integers(low = 500, high = 6000, size = 5)
print('Salários: ', salarios, '\n')

# Apresenta a média salarial
media_salarial = np.mean(salarios)
print('Média salarial: ', media_salarial, '\n')

salarios_acima_media_1 = np.where(salarios > media_salarial)
print(f'Posição no array dos salários acima de {media_salarial}: ', salarios_acima_media_1[0], '\n')

print(f'Valor dos salários acima de {media_salarial}: ', salarios[salarios_acima_media_1], '\n')

salarios_acima_media_2 = salarios[salarios > media_salarial]
print(salarios_acima_media_2)

Salários:  [ 990 4756 4100 2913 2881] 

Média salarial:  3128.0 

Posição no array dos salários acima de 3128.0:  [1 2] 

Valor dos salários acima de 3128.0:  [4756 4100] 

[4756 4100]


In [44]:
# Define uma seed para valores aleatórios
aleatorio = np.random.default_rng(seed = 42)

# Define um conjunto de valores aleatórios
salarios = aleatorio.integers(low = 500, high = 6000, size = 5)
print('Salários: ', salarios, '\n')

salarios_modificado = np.where(salarios >= media_salarial, True, 'Salários pequenos')
print(salarios_modificado, '\n')

salarios_modificado = np.where(salarios >= media_salarial, salarios * 1.1, salarios)
print(salarios_modificado)

Salários:  [ 990 4756 4100 2913 2881] 

['Salários pequenos' 'True' 'True' 'Salários pequenos' 'Salários pequenos'] 

[ 990.  5231.6 4510.  2913.  2881. ]


In [48]:
np.where((salarios >= 2900) & (salarios <= 5000))

salarios[(salarios >= 2900) & (salarios <= 5000)]

np.where((salarios >= 2900) & (salarios <= 5000), True, 'oi')

array(['oi', 'True', 'True', 'True', 'oi'], dtype='<U5')

In [52]:
np.where((salarios <= 2900) | (salarios >= 5000))

salarios[(salarios <= 2900) | (salarios >= 5000)]

np.where((salarios <= 2900) | (salarios >= 5000), True, 'oi')

array(['True', 'oi', 'oi', 'oi', 'True'], dtype='<U5')

In [41]:
# Define uma instância para a geração de números aleatórios
aleatorio = np.random.default_rng(seed = 12)

# Cria um array com valores aleatórios e inteiros
valores = aleatorio.integers(low = 100, high = 501, size = 14)
print(valores, '\n')

# Apresenta a quantidade de dimensões do vetor/matriz
qtd_dimensoes = valores.ndim
print('A quantidade de dimensões é: ', qtd_dimensoes, '\n')

# Apresenta o formato
formato = valores.shape
print('O formato do vetor/matriz é: ', formato)

[345 200 490 479 125 175 179 171 333 240 293 192 481 368] 

A quantidade de dimensões é:  1 

O formato do vetor/matriz é:  (14,)


In [90]:
valores_reshaped_1 = np.reshape(valores, (2, 7))
print(valores_reshaped_1, '\n')

valores_reshaped_2 = valores.reshape(2, 7)
print(valores_reshaped_2, '\n')

# o '-1' serve para completar o formato
valores_reshaped_3 = np.reshape(valores, (2, -1))
print(valores_reshaped_3, '\n')

# Apresenta a quantidade de dimensões do vetor/matriz
qtd_dimensoes = valores_reshaped_2.ndim
print('A quantidade de dimensões é: ', qtd_dimensoes, '\n')

# Apresenta o formato
formato = valores_reshaped_2.shape
print('O formato do vetor/matriz é: ', formato)

[[345 200 490 479 125 175 179]
 [171 333 240 293 192 481 368]] 

[[345 200 490 479 125 175 179]
 [171 333 240 293 192 481 368]] 

[[345 200 490 479 125 175 179]
 [171 333 240 293 192 481 368]] 

A quantidade de dimensões é:  2 

O formato do vetor/matriz é:  (2, 7)


In [50]:
soma_colunas = valores_reshaped_2.sum(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.sum(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [516 533 730 772 317 656 547] 

Soma das linhas:  [1993 2078]


In [51]:
soma_colunas = valores_reshaped_2.mean(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.mean(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [258.  266.5 365.  386.  158.5 328.  273.5] 

Soma das linhas:  [284.71428571 296.85714286]


In [52]:
soma_colunas = valores_reshaped_2.max(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.max(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [345 333 490 479 192 481 368] 

Soma das linhas:  [490 481]


In [53]:
soma_colunas = valores_reshaped_2.min(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.min(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [171 200 240 293 125 175 179] 

Soma das linhas:  [125 171]


<span style="color: #FFC107; font-size: 22px;">**np.arange()**</span>

In [72]:
a = np.arange(15)
print(a, '\n')

b = np.arange(8, 22)
print(b, '\n')

c = np.arange(5, 15, 0.3)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21] 

[ 5.   5.3  5.6  5.9  6.2  6.5  6.8  7.1  7.4  7.7  8.   8.3  8.6  8.9
  9.2  9.5  9.8 10.1 10.4 10.7 11.  11.3 11.6 11.9 12.2 12.5 12.8 13.1
 13.4 13.7 14.  14.3 14.6 14.9]


<span style="color: #FFC107; font-size: 22px;">**np.linspace()**</span>

In [99]:
a = np.linspace(0,8,3)
print(a, '\n')

tamanho_a = a.size
print('Tamanho: ', tamanho_a, '\n', '-' * 80)

b = np.linspace(0,8,10)
print(b, '\n')

tamanho_b = b.size
print('Tamanho: ', tamanho_b, '\n', '-' * 80)

c = np.linspace(0,8,30)
print(c, '\n')

tamanho_c = c.size
print('Tamanho: ', tamanho_c, '\n')

[0. 4. 8.] 

Tamanho:  3 
 --------------------------------------------------------------------------------
[0.         0.88888889 1.77777778 2.66666667 3.55555556 4.44444444
 5.33333333 6.22222222 7.11111111 8.        ] 

Tamanho:  10 
 --------------------------------------------------------------------------------
[0.         0.27586207 0.55172414 0.82758621 1.10344828 1.37931034
 1.65517241 1.93103448 2.20689655 2.48275862 2.75862069 3.03448276
 3.31034483 3.5862069  3.86206897 4.13793103 4.4137931  4.68965517
 4.96551724 5.24137931 5.51724138 5.79310345 6.06896552 6.34482759
 6.62068966 6.89655172 7.17241379 7.44827586 7.72413793 8.        ] 

Tamanho:  30 



<span style="color: #FFC107; font-size: 22px;">**np.arange()**</span> <br>

<span style="color: #FFC107; font-size: 22px;">**np.reshape()**</span> <br>

<span style="color: #FFC107; font-size: 22px;">**shape**</span> <br>

<span style="color: #FFC107; font-size: 22px;">**.ndim**</span> <br>

<span style="color: #FFC107; font-size: 22px;">**.size**</span> <br>

In [15]:
arange_ = np.arange(24)
print("np.arange(24): ", arange_, '\n')

reshape_ = arange_.reshape(4,-1,2)
print(".reshape(4,-1,2): \n\n", reshape_, '\n')

shape_ = reshape_.shape
print('.shape: ', shape_, '\n')

ndim_ = reshape_.ndim
print('.ndim_: ', ndim_, '\n')

size_ = reshape_.size
print('.size_: ', size_, '\n')

np.arange(24):  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

.reshape(4,-1,2): 

 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]] 

.shape:  (4, 3, 2) 

.ndim_:  3 

.size_:  24 



<span style="color: #FFC107; font-size: 22px;">**np.zeros()**</span> <br>

In [17]:
a = np.zeros((2,2))
print(a, '\n')

b = np.zeros((3,3), dtype = int)
print(b)

[[0. 0.]
 [0. 0.]] 

[[0 0 0]
 [0 0 0]
 [0 0 0]]


<span style="color: #FFC107; font-size: 22px;">**np.ones()**</span> <br>

In [18]:
a = np.ones((2,2))
print(a, '\n')

b = np.ones((3,3), dtype = int)
print(b)

[[1. 1.]
 [1. 1.]] 

[[1 1 1]
 [1 1 1]
 [1 1 1]]


<span style="color: #FFC107; font-size: 22px;">**np.eye()**</span> <br>

In [19]:
matriz_identidade_1 = np.eye(2)
print(matriz_identidade_1, '\n')

matriz_identidade_2 = np.eye(3, dtype=int)
print(matriz_identidade_2, '\n')

matriz_identidade_3 = np.eye(4, k=-2, dtype=int)
print(matriz_identidade_3, '\n')

[[1. 0.]
 [0. 1.]] 

[[1 0 0]
 [0 1 0]
 [0 0 1]] 

[[0 0 0 0]
 [0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]] 



<span style="color: #FFC107; font-size: 22px;">**np.empty()**</span> <br>

<span style="color: #00b4d8; font-size: 18px;">Cria um array sem inicializar seus elementos. Isso significa que os valores que ocupam a memória do array não são definidos explicitamente e podem ser qualquer coisa que já estava na memória. Ele é útil quando você vai preencher o array posteriormente, pois evita o tempo gasto inicializando os valores.</span> <br>

<span style="color: #ff0054; font-size: 18px;">Cria um array sem inicializar seus elementos. Isso significa que os valores que ocupam a memória do array não são definidos explicitamente e podem ser qualquer coisa que já estava na memória. Ele é útil quando você vai preencher o array posteriormente, pois evita o tempo gasto inicializando os valores.</span> <br>

<span style="color: #9d4edd; font-size: 18px;">Cria um array sem inicializar seus elementos. Isso significa que os valores que ocupam a memória do array não são definidos explicitamente e podem ser qualquer coisa que já estava na memória. Ele é útil quando você vai preencher o array posteriormente, pois evita o tempo gasto inicializando os valores.</span> <br>

In [171]:
m2 = np.empty((3,3))
m2

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ]])

<span style="color: #FFC107; font-size: 22px;">**np.diag()**</span> <br>

In [21]:
a = np.diag([10,5,16])
print(a, '\n')

b = np.diag(np.arange(5))
print(b)

[[10  0  0]
 [ 0  5  0]
 [ 0  0 16]] 

[[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [23]:
j = np.full((2, 2), 10)
print(j, '\n')

k = np.full((2, 3), [2,4,6])
print(k, '\n')

l = np.full((3, 3), [2,4,6])
print(l)

[[10 10]
 [10 10]] 

[[2 4 6]
 [2 4 6]] 

[[2 4 6]
 [2 4 6]
 [2 4 6]]


<span style="color: #FFC107; font-size: 22px;">**np.c_[]**</span> <br>

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.c_[a, b])
print(np.c_[a, b].shape, '\n')

c = np.array([[1,2,3]])
d = np.array([[4,5,6]])

print(np.c_[c, 0, 0, d])
print(np.c_[c, 0, 0, d].shape, '\n')

e = np.array([1])
f = np.array([[4,5,6]])

print(np.c_[e, f])
print(np.c_[e, f].shape)

<span style="color: #FFC107; font-size: 22px;">**np.allclose()**</span> <br>

In [24]:
print(np.allclose(1, 1))

print(np.allclose([3, 17], [3, 17]))

print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))

print(np.allclose([1.0, np.nan], [1.0, np.nan]))

print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

True
True
True
False
True


<span style="color: #FFC107; font-size: 22px;">**np.linalg.inv()**</span> <br>

Calcula a inversa de uma matriz.

Dada uma matriz quadrada ``A``, retorne a matriz inversa que satisfaça ``A @ ainv = ainv @ A = np.eye(A.shape[0])``

In [25]:
a = np.array([[1., 2.], [3., 4.]])
print(a, '\n')

inversa = np.linalg.inv(a)
print(inversa, '\n')

multiplicacao_matricial = a @ inversa
print(multiplicacao_matricial)

[[1. 2.]
 [3. 4.]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


<span style="color: #FFC107; font-size: 22px;">**np.linalg.det()**</span> <br>

In [3]:
a = np.array([[1., 2.], [3., 4.]])
print(a, '\n')

determinante = np.linalg.det(a)
print(determinante, '\n')

[[1. 2.]
 [3. 4.]] 

-2.0000000000000004 



<span style="color: #FFC107; font-size: 22px;">**np.linalg.solve()**</span> <br>

In [13]:
# Ax = b

A = np.array([10, 20, 30, 40]).reshape(2,2)
print(A, '\n')

b = np.array([50,110])
print(b, '\n')

x = np.linalg.solve(A, b)
print(x)

[[10 20]
 [30 40]] 

[ 50 110] 

[1. 2.]


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [28]:
# Cria uma instância para um gerador de números aleatórios
rng = np.random.default_rng(seed = 65)

# Define um gerador de distribuição normal
dados = (rng.standard_normal(100) * 10) + 17

# Define os percentis desejados para análise
vetor_percentil = [5, 10, 50, 90, 95]

# Percorre todos os percentis definidos
for i in vetor_percentil:
    percentil = np.percentile(dados, i)
    print(f"{i}º percentil: {percentil:.2f}")

5º percentil: 3.23
10º percentil: 5.30
50º percentil: 16.64
90º percentil: 34.33
95º percentil: 37.56


<span style="color: #FFC107; font-size: 22px;">**np.concatenate()**</span> <br>

In [38]:
a = np.random.randint(1, 100, 5)
print(a, '\n')

b = np.random.randint(110, 160, 3)
print(b, '\n')

c = np.concatenate((a, b))
print(c)

[19 98 89 86 81] 

[134 126 151] 

[ 19  98  89  86  81 134 126 151]


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [50]:
# Pseudo números aleatórios
np.random.seed(3)

a = np.random.random(4)
print(a)

a = np.random.rand(3,3)
print(a, '\n')

# Colocando o seed eu consigo compartilhar meu notebook que os valores aleatórios de quem for testar serão os mesmos
b = np.random.randint(low = 1, high = 11, size=(3, 3))
print(b)

b = np.random.randn(100)*100

c = np.random.rayleigh(1, 100)

[[0.5507979  0.70814782 0.29090474]
 [0.51082761 0.89294695 0.89629309]
 [0.12558531 0.20724288 0.0514672 ]] 

[[1 5 8]
 [9 2 7]
 [3 3 2]]


<span style="color: #FFC107; font-size: 22px;">**np.transpose()**</span> <br>
<span style="color: #FFC107; font-size: 22px;">**.T**</span> <br>

In [54]:
# Criando uma matriz
matriz = np.array([[1, 2], [3, 4], [5, 6]])
print(matriz, '\n')

# Transpondo a matriz usando numpy.transpose()
matriz_transposta_1 = np.transpose(matriz)
print(matriz_transposta_1, '\n')

matriz_transposta_2 = matriz.T
print(matriz_transposta_2)

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]] 

[[1 3 5]
 [2 4 6]]


<span style="color: #FFC107; font-size: 22px;">**np.ravel()**</span> <br>

In [56]:
import numpy as np

# Criando uma matriz 2x3
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)

# Aplicando ravel
matriz_achatada = np.ravel(matriz)

print(matriz_achatada)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [70]:
# Pseudo números aleatórios
np.random.seed(3)

matriz = np.random.randint(low = 1, high = 101, size = (3,2,4))
print(matriz, '\n')

# Aplicando ravel
matriz_achatada = np.ravel(matriz)
print(matriz_achatada)

[[[25  4 57 73]
  [ 1 22 20 75]]

 [[42 11 22 39]
  [97 21 45 94]]

 [[40 15 27 82]
  [91 23 67  3]]] 

[25  4 57 73  1 22 20 75 42 11 22 39 97 21 45 94 40 15 27 82 91 23 67  3]


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [81]:
pi = np.pi
print(pi)

nan = np.nan
print(nan)

euler = np.e
print(euler)

infinito_positivo = np.inf
print(infinito_positivo)

infinito_negativo = -np.inf
print(infinito_negativo)

3.141592653589793
nan
2.718281828459045
inf
-inf


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [84]:
np.cos(5)
np.sin(5)
np.tan(5)

-3.380515006246586

<span style="color: #FFC107; font-size: 22px;">**np.unique()**</span> <br>

In [88]:
a = np.array([2, 2, 10, 11, 13, 13])

valor = np.unique(a)
print(valor)

valor, posicao = np.unique(a, return_index = True)
print(valor)

# Apresenta a posição da primeira ocorrência
print(posicao)

[ 2 10 11 13]
[ 2 10 11 13]
[0 2 3 4]


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [96]:
import numpy as np

# Criando duas matrizes de exemplo
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(A, '\n')
print(B, '\n')

# Multiplicação elemento a elemento
result = A * B
print(result, '\n')

result = A @ B
print(result, '\n')

result = np.matmul(A, B)
print(result, '\n')

result = np.dot(A, B)
print(result, '\n')

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 5 12]
 [21 32]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 



<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [103]:
np.random.seed(13)
a = np.random.randint(-10, 11, 10)

np.abs(a)

array([ 8,  6,  0,  6,  4,  8, 10,  2,  7, 10])

In [ ]:
# Forma que o professor utilizou, o random_state faz com que os valores sejam sempre os mesmos para a mesma semente
rng = np.random.RandomState(random_state)

# Forma recomendada pelo Numpy, o random_state faz com que os valores sejam sempre os mesmos para a mesma semente
rng = np.random.default_rng(random_state)

# Gera uma distribuição uniforme
x = rng.uniform(low = 2, high = 12, size = n_samples)

# Gera uma distribuição normal
y = 70 + (8 * x) + (10 * rng.standard_normal(size = n_samples))

In [105]:
a = np.array([1, 2, 3, 4])
a = a.astype(float)

b = np.array([1.9, 2.1, 3.0, 4])
b = b.astype(int)
b

array([1, 2, 3, 4])

<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [135]:
a = np.arange(1, 9)
x = a.reshape(2, -1)

b = np.array([x, x + 10, x + 100])

print(b, '\n')

vetor_r = np.r_[x, x + 10, x + 100]
print(vetor_r, '\n')

vetor_c = np.c_[x, x + 10, x + 100]
print(vetor_c)

[[[  1   2   3   4]
  [  5   6   7   8]]

 [[ 11  12  13  14]
  [ 15  16  17  18]]

 [[101 102 103 104]
  [105 106 107 108]]] 

[[  1   2   3   4]
 [  5   6   7   8]
 [ 11  12  13  14]
 [ 15  16  17  18]
 [101 102 103 104]
 [105 106 107 108]] 

[[  1   2   3   4  11  12  13  14 101 102 103 104]
 [  5   6   7   8  15  16  17  18 105 106 107 108]]


<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [146]:
a = np.arange(1, 16)
a = a.reshape(3, -1)
print(a, '\n')

a[0,:]
a[:,0]
a[:,[1,2,0,0,0,2]]
# a[[1,0,1],:]
x[:,[0]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 



array([[ 2,  3,  1,  1,  1,  3],
       [ 7,  8,  6,  6,  6,  8],
       [12, 13, 11, 11, 11, 13]])

<span style="color: #FFC107; font-size: 22px;">**np.full()**</span> <br>

In [161]:
a = np.array([2, 15, 13, 3])

np.std(a)

somatorio = np.sum(a)
tamanho = a.size
media = somatorio / tamanho

np.sqrt(np.sum(((a - media) ** 2)) / tamanho)
np.var(a)
np.sum(((a - media) ** 2)) / tamanho + 0

33.6875

<span style="color: #FFC107; font-size: 22px;">**Broadcasting**</span> <br>


<span style="color: #00b4d8; font-size: 18px;">O broadcasting no NumPy é uma funcionalidade poderosa que permite realizar operações em arrays de diferentes formas (dimensões) de maneira eficiente, sem a necessidade de copiar dados ou ajustar explicitamente o tamanho dos arrays. Ele é aplicado automaticamente quando se realiza operações entre arrays de formas diferentes, permitindo que o NumPy "alargue" (ou "transmita", de onde vem o termo broadcast) o menor array para que ele tenha uma forma compatível com o maior array.</span> <br>

<span style="color: #7abf66; font-size: 18px;">O broadcasting no NumPy é uma funcionalidade poderosa que permite realizar operações em arrays de diferentes formas (dimensões) de maneira eficiente, sem a necessidade de copiar dados ou ajustar explicitamente o tamanho dos arrays. Ele é aplicado automaticamente quando se realiza operações entre arrays de formas diferentes, permitindo que o NumPy "alargue" (ou "transmita", de onde vem o termo broadcast) o menor array para que ele tenha uma forma compatível com o maior array.</span> <br>

In [172]:
import numpy as np

# Array 1: forma (3, 1)
a = np.array([[1], [2], [3]])

# Array 2: forma (1, 4)
b = np.array([10, 20, 30, 40])

# Operação: soma de 'a' e 'b'
result = a + b
print(result)

[[11 21 31 41]
 [12 22 32 42]
 [13 23 33 43]]


In [173]:
a = np.array([1, 2, 3])      # forma (3,)
b = np.array([[10], [20], [30]])  # forma (3, 1)

# Operação: multiplicação
result = a * b
print(result)

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # Forma (2, 3)
b = np.array([10, 20, 30])            # Forma (3,)
result = a + b
print(result)

In [ ]:
a = np.array([[1], [2], [3]])  # Forma (3, 1)
b = np.array([10, 20, 30])     # Forma (3,)
result = a * b
print(result)

<span style="color: #FFC107; font-size: 22px;">**Trigonometric Functions**</span> <br>

In [187]:
import numpy as np

# Exemplo para np.sin
# Calcula o seno de um ângulo (em radianos).
x = np.pi / 2
print("np.sin:", np.sin(x))  # Saída: 1.0

# Exemplo para np.cos
# Calcula o cosseno de um ângulo (em radianos).
x = np.pi
print("np.cos:", np.cos(x))  # Saída: -1.0

# Exemplo para np.tan
# Calcula a tangente de um ângulo (em radianos).
x = np.pi / 4
print("np.tan:", np.tan(x))  # Saída: 1.0

# Exemplo para np.arcsin
# Calcula o arco seno (inverso do seno) de um valor, retornando o ângulo em radianos.
x = 1
print("np.arcsin:", np.arcsin(x))  # Saída: 1.5707963267948966 (π/2)

# Exemplo para np.arccos
# Calcula o arco cosseno (inverso do cosseno) de um valor, retornando o ângulo em radianos.
x = 1
print("np.arccos:", np.arccos(x))  # Saída: 0.0

# Exemplo para np.arctan
# Calcula o arco tangente (inverso da tangente) de um valor, retornando o ângulo em radianos.
x = 1
print("np.arctan:", np.arctan(x))  # Saída: 0.7853981633974483 (π/4)

# Exemplo para np.hypot
# Calcula a hipotenusa de um triângulo retângulo com lados x e y.
x, y = 3, 4
print("np.hypot:", np.hypot(x, y))  # Saída: 5.0

# Exemplo para np.arctan2
# Calcula o arco tangente do quociente de seus argumentos, retornando o ângulo em radianos.
y, x = 1, 1
print("np.arctan2:", np.arctan2(y, x))  # Saída: 0.7853981633974483 (π/4)

# Exemplo para np.degrees
# Converte um ângulo de radianos para graus.
x = np.pi
print("np.degrees:", np.degrees(x))  # Saída: 180.0
print(f"np.degrees: {np.degrees(x) = }")

# Exemplo para np.radians
# Converte um ângulo de graus para radianos.
x = 180
print("np.radians:", np.radians(x))  # Saída: 3.141592653589793 (π)

# Exemplo para np.unwrap
# Desfaz saltos de 2π em um array de ângulos.
x = np.array([0, np.pi, 2*np.pi, 3*np.pi])
print("np.unwrap:", np.unwrap(x))  # Saída: [0.         3.14159265 6.28318531 9.42477796]

# Exemplo para np.deg2rad
# Converte um ângulo de graus para radianos.
x = 180
print("np.deg2rad:", np.deg2rad(x))  # Saída: 3.141592653589793 (π)

# Exemplo para np.rad2deg
# Converte um ângulo de radianos para graus.
x = np.pi
print("np.rad2deg:", np.rad2deg(x))  # Saída: 180.0

np.sin: 1.0
np.cos: -1.0
np.tan: 0.9999999999999999
np.arcsin: 1.5707963267948966
np.arccos: 0.0
np.arctan: 0.7853981633974483
np.hypot: 5.0
np.arctan2: 0.7853981633974483
np.degrees: 180.0
np.degrees: np.degrees(x) = 180.0
np.radians: 3.141592653589793
np.unwrap: [0.         3.14159265 6.28318531 9.42477796]
np.deg2rad: 3.141592653589793
np.rad2deg: 180.0


<span style="color: #FFC107; font-size: 22px;">**Hyperbolic Functions**</span> <br>

In [185]:
# Exemplo para np.sinh
x = 1
print("np.sinh:", np.sinh(x))

# Exemplo para np.cosh
x = 1
print("np.cosh:", np.cosh(x))

# Exemplo para np.tanh
x = 1
print("np.tanh:", np.tanh(x))

# Exemplo para np.arcsinh
x = 1
print("np.arcsinh:", np.arcsinh(x))

# Exemplo para np.arccosh
x = 2
print("np.arccosh:", np.arccosh(x))

# Exemplo para np.arctanh
x = 0.5
print("np.arctanh:", np.arctanh(x))

np.sinh: 1.1752011936438014
np.cosh: 1.5430806348152437
np.tanh: 0.7615941559557649
np.arcsinh: 0.881373587019543
np.arccosh: 1.3169578969248166
np.arctanh: 0.5493061443340549


<span style="color: #FFC107; font-size: 22px;">**Rounding**</span> <br>

In [ ]:
# np.round: Arredonda para o inteiro mais próximo. Pode especificar o número de decimais.
x = 3.567
print("np.round:", np.round(x, 2))  # Arredonda para 2 casas decimais

# np.around: Funciona de forma idêntica ao np.round.
x = 3.567
print("np.around:", np.around(x, 2))  # Arredonda para 2 casas decimais

# np.rint: Arredonda para o inteiro mais próximo, mas retorna um float.
x = 3.567
print("np.rint:", np.rint(x))  # Arredonda para o inteiro mais próximo

# np.fix: Arredonda para o inteiro mais próximo em direção a zero.
x = 3.567
print("np.fix:", np.fix(x))  # Arredonda para 3
x = -3.567
print("np.fix (negativo):", np.fix(x))  # Arredonda para -3

# np.floor: Arredonda para o menor inteiro mais próximo (para baixo).
x = 3.567
print("np.floor:", np.floor(x))  # Arredonda para 3
x = -3.567
print("np.floor (negativo):", np.floor(x))  # Arredonda para -4

# np.ceil: Arredonda para o maior inteiro mais próximo (para cima).
x = 3.567
print("np.ceil:", np.ceil(x))  # Arredonda para 4
x = -3.567
print("np.ceil (negativo):", np.ceil(x))  # Arredonda para -3

# np.trunc: Trunca o valor, removendo a parte decimal.
x = 3.567
print("np.trunc:", np.trunc(x))  # Trunca para 3
x = -3.567
print("np.trunc (negativo):", np.trunc(x))  # Trunca para -3

<span style="color: #FFC107; font-size: 22px;">**Sums, products, differences**</span> <br>

In [188]:
import numpy as np

# Exemplo para np.prod
# Calcula o produto de todos os elementos de um array.
arr = np.array([1, 2, 3, 4])
print("np.prod:", np.prod(arr))  # Saída: 24

# Exemplo para np.sum
# Calcula a soma de todos os elementos de um array.
arr = np.array([1, 2, 3, 4])
print("np.sum:", np.sum(arr))  # Saída: 10

# Exemplo para np.nanprod
# Calcula o produto de todos os elementos de um array, tratando NaNs como 1.
arr = np.array([1, 2, np.nan, 4])
print("np.nanprod:", np.nanprod(arr))  # Saída: 8.0

# Exemplo para np.nansum
# Calcula a soma de todos os elementos de um array, tratando NaNs como 0.
arr = np.array([1, 2, np.nan, 4])
print("np.nansum:", np.nansum(arr))  # Saída: 7.0

# Exemplo para np.cumsum
# Calcula a soma cumulativa dos elementos de um array.
arr = np.array([1, 2, 3, 4])
print("np.cumsum:", np.cumsum(arr))  # Saída: [ 1  3  6 10]

# Exemplo para np.cumprod
# Calcula o produto cumulativo dos elementos de um array.
arr = np.array([1, 2, 3, 4])
print("np.cumprod:", np.cumprod(arr))  # Saída: [ 1  2  6 24]

# Exemplo para np.nancumprod
# Calcula o produto cumulativo dos elementos de um array, tratando NaNs como 1.
arr = np.array([1, 2, np.nan, 4])
print("np.nancumprod:", np.nancumprod(arr))  # Saída: [ 1.  2.  2.  8.]

# Exemplo para np.nancumsum
# Calcula a soma cumulativa dos elementos de um array, tratando NaNs como 0.
arr = np.array([1, 2, np.nan, 4])
print("np.nancumsum:", np.nancumsum(arr))  # Saída: [ 1.  3.  3.  7.]

# Exemplo para np.diff
# Calcula a diferença entre elementos consecutivos de um array.
arr = np.array([1, 2, 4, 7])
print("np.diff:", np.diff(arr))  # Saída: [1 2 3]

# Exemplo para np.ediff1d
# Calcula a diferença entre elementos consecutivos de um array, retornando um array 1D.
arr = np.array([1, 2, 4, 7])
print("np.ediff1d:", np.ediff1d(arr))  # Saída: [1 2 3]

# Exemplo para np.gradient
# Calcula o gradiente de um array.
arr = np.array([1, 2, 4, 7])
print("np.gradient:", np.gradient(arr))  # Saída: [1.  1.5 2.5 3. ]

# Exemplo para np.cross
# Calcula o produto vetorial de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.cross:", np.cross(a, b))  # Saída: [-3  6 -3]

# Exemplo para np.trapezoid
# Calcula a integral de um array usando a regra do trapézio.
y = np.array([1, 2, 3])
print("np.trapezoid:", np.trapz(y))  # Saída: 4.0

np.prod: 24
np.sum: 10
np.nanprod: 8.0
np.nansum: 7.0
np.cumsum: [ 1  3  6 10]
np.cumprod: [ 1  2  6 24]
np.nancumprod: [1. 2. 2. 8.]
np.nancumsum: [1. 3. 3. 7.]
np.diff: [1 2 3]
np.ediff1d: [1 2 3]
np.gradient: [1.  1.5 2.5 3. ]
np.cross: [-3  6 -3]
np.trapezoid: 4.0


<span style="color: #FFC107; font-size: 22px;">**Exponents and logarithms**</span> <br>

In [ ]:
import numpy as np

# Exemplo para np.exp
# Calcula a exponencial de todos os elementos do array.
x = np.array([1, 2, 3])
print("np.exp:", np.exp(x))  # Saída: [ 2.71828183  7.3890561  20.08553692]

# Exemplo para np.expm1
# Calcula a exponencial de todos os elementos do array, subtraindo 1.
x = np.array([1, 2, 3])
print("np.expm1:", np.expm1(x))  # Saída: [ 1.71828183  6.3890561  19.08553692]

# Exemplo para np.exp2
# Calcula 2 elevado à potência de todos os elementos do array.
x = np.array([1, 2, 3])
print("np.exp2:", np.exp2(x))  # Saída: [2. 4. 8.]

# Exemplo para np.log
# Calcula o logaritmo natural (base e) de todos os elementos do array.
x = np.array([1, np.e, np.e**2])
print("np.log:", np.log(x))  # Saída: [0. 1. 2.]

# Exemplo para np.log10
# Calcula o logaritmo na base 10 de todos os elementos do array.
x = np.array([1, 10, 100])
print("np.log10:", np.log10(x))  # Saída: [0. 1. 2.]

# Exemplo para np.log2
# Calcula o logaritmo na base 2 de todos os elementos do array.
x = np.array([1, 2, 4])
print("np.log2:", np.log2(x))  # Saída: [0. 1. 2.]

# Exemplo para np.log1p
# Calcula o logaritmo natural (base e) de (1 + todos os elementos do array).
x = np.array([1, np.e-1, np.e**2-1])
print("np.log1p:", np.log1p(x))  # Saída: [1. 1. 2.]

# Exemplo para np.logaddexp
# Calcula o logaritmo da soma das exponenciais de entrada.
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print("np.logaddexp:", np.logaddexp(a, b))  # Saída: [2.31326169 3.31326169 4.31326169]

# Exemplo para np.logaddexp2
# Calcula o logaritmo da soma das exponenciais de entrada na base 2.
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print("np.logaddexp2:", np.logaddexp2(a, b))  # Saída: [2.5849625 3.5849625 4.5849625]

<span style="color: #FFC107; font-size: 22px;">**Other special functions**</span> <br>

In [189]:
import numpy as np

# Exemplo para np.i0
# Calcula a função de Bessel modificada de primeira espécie de ordem zero para todos os elementos do array.
x = np.array([0, 1, 2, 3])
print("np.i0:", np.i0(x))  # Saída: [1.         1.26606588 2.2795853  4.88079259]

# Exemplo para np.sinc
# Calcula a função sinc normalizada (sin(πx)/(πx)) para todos os elementos do array.
x = np.array([0, 1, 2, 3])
print("np.sinc:", np.sinc(x))  # Saída: [ 1.00000000e+00  3.89817183e-17 -3.89817183e-17  3.89817183e-17]

np.i0: [1.         1.26606588 2.2795853  4.88079259]
np.sinc: [ 1.00000000e+00  3.89817183e-17 -3.89817183e-17  3.89817183e-17]


<span style="color: #FFC107; font-size: 22px;">**Floating point routines**</span> <br>

In [195]:
import numpy as np

# Exemplo para np.signbit
# Retorna True onde o sinal do número é negativo.
x = np.array([-1, 0, 1])
print("np.signbit:", np.signbit(x))  # Saída: [ True False False]

# Exemplo para np.copysign
# Copia o sinal de um número para outro.
x = -1
y = 2
print("np.copysign:", np.copysign(y, x))  # Saída: -2.0

# Exemplo para np.frexp
# Decompõe o número em sua mantissa e expoente.
x = 8
mantissa, exponent = np.frexp(x)
print("np.frexp:", mantissa, exponent)  # Saída: 0.5 4

# Exemplo para np.ldexp
# Calcula x * (2**exp).
mantissa = 0.5
exponent = 4
print("np.ldexp:", np.ldexp(mantissa, exponent))  # Saída: 8.0

# Exemplo para np.nextafter
# Retorna o próximo valor de ponto flutuante após x na direção de y.
x = 1.0
y = 2.0
print("np.nextafter:", np.nextafter(x, y))  # Saída: 1.0000000000000002

# Exemplo para np.spacing
# Retorna a distância entre x e o próximo valor representável.
x = 1.0
print("np.spacing:", np.spacing(x))  # Saída: 2.220446049250313e-16

np.signbit: [ True False False]
np.copysign: -2.0
np.frexp: 0.5 4
np.ldexp: 8.0
np.nextafter: 1.0000000000000002
np.spacing: 2.220446049250313e-16


<span style="color: #FFC107; font-size: 22px;">**Rational routines**</span> <br>

In [196]:
import numpy as np

# Exemplo para np.lcm
# Calcula o mínimo múltiplo comum (MMC) de dois números ou arrays.
x = 12
y = 15
print("np.lcm:", np.lcm(x, y))  # Saída: 60

# Exemplo para np.gcd
# Calcula o maior divisor comum (MDC) de dois números ou arrays.
x = 12
y = 15
print("np.gcd:", np.gcd(x, y))  # Saída: 3

np.lcm: 60
np.gcd: 3


<span style="color: #FFC107; font-size: 22px;">**Arithmetic operations**</span> <br>

In [198]:
import numpy as np

# Exemplo para np.add
# Soma os elementos de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.add:", np.add(a, b))  # Saída: [5 7 9]

# Exemplo para np.reciprocal
# Calcula o recíproco (1/x) de cada elemento do array.
a = np.array([1, 2, 4])
print("np.reciprocal:", np.reciprocal(a))  # Saída: [1 0 0] (inteiros)

# Exemplo para np.positive
# Retorna o valor positivo de cada elemento do array.
a = np.array([-1, -2, 3])
print("np.positive:", np.positive(a))  # Saída: [-1 -2  3]

# Exemplo para np.negative
# Retorna o valor negativo de cada elemento do array.
a = np.array([1, -2, 3])
print("np.negative:", np.negative(a))  # Saída: [-1  2 -3]

# Exemplo para np.multiply
# Multiplica os elementos de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.multiply:", np.multiply(a, b))  # Saída: [ 4 10 18]

# Exemplo para np.divide
# Divide os elementos de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.divide:", np.divide(a, b))  # Saída: [0.25 0.4  0.5 ]

# Exemplo para np.power
# Eleva os elementos de um array à potência dos elementos de outro array.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.power:", np.power(a, b))  # Saída: [  1  32 729]

# Exemplo para np.subtract
# Subtrai os elementos de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.subtract:", np.subtract(a, b))  # Saída: [-3 -3 -3]

# Exemplo para np.true_divide
# Divide os elementos de dois arrays, retornando um resultado de ponto flutuante.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.true_divide:", np.true_divide(a, b))  # Saída: [0.25 0.4  0.5 ]

# Exemplo para np.floor_divide
# Divide os elementos de dois arrays, retornando o maior inteiro menor ou igual ao resultado.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.floor_divide:", np.floor_divide(a, b))  # Saída: [0 0 0]

# Exemplo para np.float_power
# Eleva os elementos de um array à potência dos elementos de outro array, retornando um resultado de ponto flutuante.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.float_power:", np.float_power(a, b))  # Saída: [  1.  32. 729.]

# Exemplo para np.fmod
# Calcula o resto da divisão dos elementos de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.fmod:", np.fmod(a, b))  # Saída: [1 2 3]

# Exemplo para np.mod
# Calcula o resto da divisão dos elementos de dois arrays (mesma função que np.fmod).
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.mod:", np.mod(a, b))  # Saída: [1 2 3]

# Exemplo para np.modf
# Decompõe os elementos de um array em suas partes inteira e fracionária.
a = np.array([1.5, 2.5, 3.5])
frac, whole = np.modf(a)
print("np.modf:", frac, whole)  # Saída: [0.5 0.5 0.5] [1. 2. 3.]

# Exemplo para np.remainder
# Calcula o resto da divisão dos elementos de dois arrays (mesma função que np.mod).
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("np.remainder:", np.remainder(a, b))  # Saída: [1 2 3]

# Exemplo para np.divmod
# Calcula o quociente e o resto da divisão dos elementos de dois arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
quotient, remainder = np.divmod(a, b)
print("np.divmod:", quotient, remainder)  # Saída: [0 0 0] [1 2 3]

np.add: [5 7 9]
np.reciprocal: [1 0 0]
np.positive: [-1 -2  3]
np.negative: [-1  2 -3]
np.multiply: [ 4 10 18]
np.divide: [0.25 0.4  0.5 ]
np.power: [  1  32 729]
np.subtract: [-3 -3 -3]
np.true_divide: [0.25 0.4  0.5 ]
np.floor_divide: [0 0 0]
np.float_power: [  1.  32. 729.]
np.fmod: [1 2 3]
np.mod: [1 2 3]
np.modf: [0.5 0.5 0.5] [1. 2. 3.]
np.remainder: [1 2 3]
np.divmod: [0 0 0] [1 2 3]


<span style="color: #FFC107; font-size: 22px;">**Handling complex numbers**</span> <br>

In [199]:
import numpy as np

# Exemplo para np.angle
# Retorna o ângulo (fase) de números complexos em radianos.
z = np.array([1+1j, 1-1j, -1+1j, -1-1j])
print("np.angle:", np.angle(z))  # Saída: [ 0.78539816 -0.78539816  2.35619449 -2.35619449]

# Exemplo para np.real
# Retorna a parte real de números complexos.
z = np.array([1+1j, 1-1j, -1+1j, -1-1j])
print("np.real:", np.real(z))  # Saída: [ 1.  1. -1. -1.]

# Exemplo para np.imag
# Retorna a parte imaginária de números complexos.
z = np.array([1+1j, 1-1j, -1+1j, -1-1j])
print("np.imag:", np.imag(z))  # Saída: [ 1. -1.  1. -1.]

# Exemplo para np.conj
# Retorna o conjugado complexo de números complexos.
z = np.array([1+1j, 1-1j, -1+1j, -1-1j])
print("np.conj:", np.conj(z))  # Saída: [ 1.-1.j  1.+1.j -1.-1.j -1.+1.j]

# Exemplo para np.conjugate
# Retorna o conjugado complexo de números complexos (mesma função que np.conj).
z = np.array([1+1j, 1-1j, -1+1j, -1-1j])
print("np.conjugate:", np.conjugate(z))  # Saída: [ 1.-1.j  1.+1.j -1.-1.j -1.+1.j]

np.angle: [ 0.78539816 -0.78539816  2.35619449 -2.35619449]
np.real: [ 1.  1. -1. -1.]
np.imag: [ 1. -1.  1. -1.]
np.conj: [ 1.-1.j  1.+1.j -1.-1.j -1.+1.j]
np.conjugate: [ 1.-1.j  1.+1.j -1.-1.j -1.+1.j]


<span style="color: #FFC107; font-size: 22px;">**Extrema finding**</span> <br>

In [200]:
import numpy as np

# Exemplo para np.max
# Retorna o valor máximo de um array.
arr = np.array([1, 2, 3, 4, 5])
print("np.max:", np.max(arr))  # Saída: 5

# Exemplo para np.amax
# Funciona de forma idêntica ao np.max.
arr = np.array([1, 2, 3, 4, 5])
print("np.amax:", np.amax(arr))  # Saída: 5

# Exemplo para np.fmax
# Retorna o valor máximo, elemento a elemento, comparando dois arrays, ignorando NaNs.
arr1 = np.array([1, 2, np.nan, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("np.fmax:", np.fmax(arr1, arr2))  # Saída: [5. 4. 3. 4. 5.]

# Exemplo para np.nanmax
# Retorna o valor máximo de um array, ignorando NaNs.
arr = np.array([1, 2, np.nan, 4, 5])
print("np.nanmax:", np.nanmax(arr))  # Saída: 5.0

# Exemplo para np.minimum
# Retorna o valor mínimo, elemento a elemento, comparando dois arrays.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("np.minimum:", np.minimum(arr1, arr2))  # Saída: [1 2 3 2 1]

# Exemplo para np.min
# Retorna o valor mínimo de um array.
arr = np.array([1, 2, 3, 4, 5])
print("np.min:", np.min(arr))  # Saída: 1

# Exemplo para np.amin
# Funciona de forma idêntica ao np.min.
arr = np.array([1, 2, 3, 4, 5])
print("np.amin:", np.amin(arr))  # Saída: 1

# Exemplo para np.fmin
# Retorna o valor mínimo, elemento a elemento, comparando dois arrays, ignorando NaNs.
arr1 = np.array([1, 2, np.nan, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("np.fmin:", np.fmin(arr1, arr2))  # Saída: [1. 2. 3. 2. 1.]

# Exemplo para np.nanmin
# Retorna o valor mínimo de um array, ignorando NaNs.
arr = np.array([1, 2, np.nan, 4, 5])
print("np.nanmin:", np.nanmin(arr))  # Saída: 1.0import numpy as np

# Exemplo para np.max
# Retorna o valor máximo de um array.
arr = np.array([1, 2, 3, 4, 5])
print("np.max:", np.max(arr))  # Saída: 5

# Exemplo para np.amax
# Funciona de forma idêntica ao np.max.
arr = np.array([1, 2, 3, 4, 5])
print("np.amax:", np.amax(arr))  # Saída: 5

# Exemplo para np.fmax
# Retorna o valor máximo, elemento a elemento, comparando dois arrays, ignorando NaNs.
arr1 = np.array([1, 2, np.nan, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("np.fmax:", np.fmax(arr1, arr2))  # Saída: [5. 4. 3. 4. 5.]

# Exemplo para np.nanmax
# Retorna o valor máximo de um array, ignorando NaNs.
arr = np.array([1, 2, np.nan, 4, 5])
print("np.nanmax:", np.nanmax(arr))  # Saída: 5.0

# Exemplo para np.minimum
# Retorna o valor mínimo, elemento a elemento, comparando dois arrays.
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("np.minimum:", np.minimum(arr1, arr2))  # Saída: [1 2 3 2 1]

# Exemplo para np.min
# Retorna o valor mínimo de um array.
arr = np.array([1, 2, 3, 4, 5])
print("np.min:", np.min(arr))  # Saída: 1

# Exemplo para np.amin
# Funciona de forma idêntica ao np.min.
arr = np.array([1, 2, 3, 4, 5])
print("np.amin:", np.amin(arr))  # Saída: 1

# Exemplo para np.fmin
# Retorna o valor mínimo, elemento a elemento, comparando dois arrays, ignorando NaNs.
arr1 = np.array([1, 2, np.nan, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])
print("np.fmin:", np.fmin(arr1, arr2))  # Saída: [1. 2. 3. 2. 1.]

# Exemplo para np.nanmin
# Retorna o valor mínimo de um array, ignorando NaNs.
arr = np.array([1, 2, np.nan, 4, 5])
print("np.nanmin:", np.nanmin(arr))  # Saída: 1.0

np.max: 5
np.amax: 5
np.fmax: [5. 4. 3. 4. 5.]
np.nanmax: 5.0
np.minimum: [1 2 3 2 1]
np.min: 1
np.amin: 1
np.fmin: [1. 2. 3. 2. 1.]
np.nanmin: 1.0
np.max: 5
np.amax: 5
np.fmax: [5. 4. 3. 4. 5.]
np.nanmax: 5.0
np.minimum: [1 2 3 2 1]
np.min: 1
np.amin: 1
np.fmin: [1. 2. 3. 2. 1.]
np.nanmin: 1.0


<span style="color: #FFC107; font-size: 22px;">**Miscellaneous**</span> <br>

In [202]:
import numpy as np

# Exemplo para np.convolve
# Realiza a convolução de dois arrays.
a = np.array([1, 2, 3])
b = np.array([0, 1, 0.5])
print("np.convolve:", np.convolve(a, b))  # Saída: [0.  1.  2.5 4.  1.5]

# Exemplo para np.clip
# Limita os valores de um array a um intervalo especificado.
a = np.array([1, 2, 3, 4, 5])
print("np.clip:", np.clip(a, 2, 4))  # Saída: [2 2 3 4 4]

# Exemplo para np.sqrt
# Calcula a raiz quadrada de cada elemento do array.
a = np.array([1, 4, 9, 16])
print("np.sqrt:", np.sqrt(a))  # Saída: [1. 2. 3. 4.]

# Exemplo para np.cbrt
# Calcula a raiz cúbica de cada elemento do array.
a = np.array([1, 8, 27, 64])
print("np.cbrt:", np.cbrt(a))  # Saída: [1. 2. 3. 4.]

# Exemplo para np.square
# Calcula o quadrado de cada elemento do array.
a = np.array([1, 2, 3, 4])
print("np.square:", np.square(a))  # Saída: [ 1  4  9 16]

# Exemplo para np.absolute
# Calcula o valor absoluto de cada elemento do array.
a = np.array([-1, -2, 3, -4])
print("np.absolute:", np.absolute(a))  # Saída: [1 2 3 4]

# Exemplo para np.fabs
# Calcula o valor absoluto de cada elemento do array (mesma função que np.absolute).
a = np.array([-1, -2, 3, -4])
print("np.fabs:", np.fabs(a))  # Saída: [1. 2. 3. 4.]

# Exemplo para np.sign
# Retorna um array com os sinais dos elementos do array original.
a = np.array([-2, -1, 0, 1, 2])
print("np.sign:", np.sign(a))  # Saída: [-1 -1  0  1  1]

# Exemplo para np.heaviside
# Calcula a função de Heaviside para cada elemento do array.
a = np.array([-1, 0, 2])
print("np.heaviside:", np.heaviside(a, 0.5))  # Saída: [0.  0.5 1. ]

# Exemplo para np.nan_to_num
# Substitui NaNs por zero e infinitos por valores finitos grandes.
a = np.array([1, 2, np.nan, np.inf, -np.inf])
print("np.nan_to_num:", np.nan_to_num(a))  # Saída: [ 1.00000000e+000  2.00000000e+000  0.00000000e+000  1.79769313e+308 -1.79769313e+308]

# Exemplo para np.nan
# Representa um valor NaN (Not a Number).
print("np.nan:", np.nan)  # Saída: nan

# Exemplo para np.real_if_close
# Retorna a parte real de um número complexo se a parte imaginária for pequena.
a = np.array([1+1e-10j, 1+1j])
print("np.real_if_close:", np.real_if_close(a, tol=1000))  # Saída: [1.+0.j 1.+1.j]

# Exemplo para np.interp
# Realiza a interpolação linear de um conjunto de pontos.
x = np.array([0, 1, 2])
xp = np.array([0, 1, 2])
fp = np.array([0, 1, 4])
print("np.interp:", np.interp(x, xp, fp))  # Saída: [0. 1. 4.]

# Exemplo para np.bitwise_count
# Conta o número de bits definidos em cada elemento do array.
a = np.array([0, 1, 2, 3])
print("np.bitwise_count:", np.unpackbits(a.astype(np.uint8)))  # Saída: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]

np.convolve: [0.  1.  2.5 4.  1.5]
np.clip: [2 2 3 4 4]
np.sqrt: [1. 2. 3. 4.]
np.cbrt: [1. 2. 3. 4.]
np.square: [ 1  4  9 16]
np.absolute: [1 2 3 4]
np.fabs: [1. 2. 3. 4.]
np.sign: [-1 -1  0  1  1]
np.heaviside: [0.  0.5 1. ]
np.nan_to_num: [ 1.00000000e+000  2.00000000e+000  0.00000000e+000  1.79769313e+308
 -1.79769313e+308]
np.nan: nan
np.real_if_close: [1.+1.e-10j 1.+1.e+00j]
np.interp: [0. 1. 4.]
np.bitwise_count: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1]
