<span style="color: #FFC107; font-size: 22px;">Referências</span>

1. [Documentação do Numpy](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

<span style="color: #FFC107; font-size: 22px;">Importação das bibliotecas</span>

In [2]:
import numpy as np
import time

<span style="color: #FFC107; font-size: 22px;">**np.array()**</span> <br>

<span style="color: #FFC107; font-size: 18px;">No Numpy, todos os elementos de um `array` são do mesmo tipo.</span>

<span style="color: #FFC107; font-size: 18px;">Caso inicialmente eles sejam de tipos diferentes, o numpy altera para um formato mais genérico.</span>

In [6]:
# Definindo os elementos da lista
lista_elementos = [24, "Bom dia", 3.7]

# Percorrendo todos os elementos da lista
for elemento in lista_elementos:

    # Apresentando o tipo do elemento
    print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos do array
np_lista = np.array(lista_elementos)

# Percorrendo todos os elementos do array
for elemento in np_lista:

    # Apresentando o tipo do elemento
    print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos da lista
lista_elementos = [24, 2.5 , 9, 3.7]

# Percorrendo todos os elementos da lista
for elemento in lista_elementos:

    # Apresentando o tipo do elemento
    print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos do array
np_lista = np.array(lista_elementos)

# Percorrendo todos os elementos do array
for elemento in np_lista:

    # Apresentando o tipo do elemento
    print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

<class 'int'>
<class 'float'>
<class 'int'>
<class 'float'>

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


<span style="color: #FFC107; font-size: 18px;">Na lista não é possível somar um número qualquer de forma direta.</span>

<span style="color: #FFC107; font-size: 18px;">Já em um array do Numpy isso é possível.</span>

In [20]:
# Cria uma lista de números
lista_numeros = [1, 2, 3, 4]

# Acrescenta o número 1 a lista
lista_numeros = lista_numeros + [1]

# Apresenta a lista de números com o acréscimo do número 2
print(lista_numeros)

#=====================================================================

# Cria um array
np_numeros = np.array(lista_numeros)

# Soma o número 1 ao array
np_numeros = np_numeros + 1

# Apresenta a soma do número 1 ao array
print(np_numeros)

[1, 2, 3, 4, 1]
[2 3 4 5 2]


In [102]:
# 1 dimensão
e = np.array([7,5,3,16,39])
print(e)

# 2 dimensões
f = np.array([(6,4,2),(3,8,1)])
print(f)

# 3 dimensões
g = np.array([(52,63,74),(96,2,15),(28,13,47)])
print(g)

g = np.array([[52,63,74], [96,2,15], [28,13,47]])
print(g)

[ 7  5  3 16 39]
[[6 4 2]
 [3 8 1]]
[[52 63 74]
 [96  2 15]
 [28 13 47]]
[[52 63 74]
 [96  2 15]
 [28 13 47]]


<span style="color: #FFC107; font-size: 18px;">O tempo de processamento de um variável Numpy é mais rápido.</span>

In [12]:
# Lista com números de 1 à 10.000.000
lista = list(range(1, 20_000_000))

# Tempo inicial
inicio_lista = time.time()

# Calcula todos os elementos da lista
soma_lista = sum(lista)

# Tempo final
fim_lista = time.time()

# Calcula o tempo necessário para calcular os elementos da lista
duracao_lista = fim_lista - inicio_lista

# Apresenta a duração para somar todos os números da lista
print(f'O tempo total para somar os elementos da lista foi de: {duracao_lista:.7f} segundos')

#================================================================================================

# Array com números de 1 à 10.000.000
array = np.array(range(1, 20_000_000))

# Tempo inicial
inicio_np = time.time()

# Calcula todos os elementos da lista
soma_lista = np.sum(array)

# Tempo final
fim_np = time.time()

# Calcula o tempo necessário para calcular os elementos da lista
duracao_np = fim_np - inicio_np

# Apresenta a duração para somar todos os números do array
print(f'O tempo total para somar os elementos do array foi de: {duracao_np:.7f} segundos')

#================================================================================================

if duracao_np != 00:
    print(f'O array do Nympy é {(duracao_lista / duracao_np):.2f} vezes mais rápido.')

O tempo total para somar os elementos da lista foi de: 0.4567010 segundos
O tempo total para somar os elementos do array foi de: 0.0000000 segundos


<span style="color: #FFC107; font-size: 22px;">**np.sum()**</span> <br>

In [8]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Soma os elementos do array
soma_vetor = np.sum(vetor)
print('Soma: ', soma_vetor)

# Soma os elementos do array
soma_vetor = vetor.sum()
print('Soma: ', soma_vetor)

Array:  [ 9  1 22  3 20 21 18]
Soma:  94
Soma:  94


<span style="color: #FFC107; font-size: 22px;">**np.mean()**</span> <br>

In [12]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Faz a média dos elementos do array
media_vetor = np.mean(vetor)
print('Média: ', media_vetor)

# Faz a média dos elementos do array
media_vetor = vetor.mean()
print('Média: ', media_vetor)


Array:  [ 9  1 22  3 20 21 18]
Média:  13.428571428571429
Média:  13.428571428571429


<span style="color: #FFC107; font-size: 22px;">**np.max()**</span> <br>

In [13]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Retorna o valor máximo do array
maximo_vetor = np.max(vetor)
print('Valor máximo: ', maximo_vetor)

# Retorna o valor máximo do array
maximo_vetor = vetor.max()
print('Valor máximo: ', maximo_vetor)

Array:  [ 9  1 22  3 20 21 18]
Valor máximo:  22
Valor máximo:  22


<span style="color: #FFC107; font-size: 22px;">**np.min()**</span>

In [14]:
# Definição do array
vetor = np.array([9, 1, 22, 3, 20, 21, 18])
print('Array: ', vetor)

# Retorna o valor mínimo do array
minimo_vetor = np.min(vetor)
print('Valor mínimo: ', minimo_vetor)

# Retorna o valor mínimo do array
minimo_vetor = vetor.min()
print('Valor mínimo: ', minimo_vetor)

Array:  [ 9  1 22  3 20 21 18]
Valor mínimo:  1
Valor mínimo:  1


<span style="color: #FFC107; font-size: 22px;">**np.sort()**</span>

<span style="color: #FFC107; font-size: 18px;">Ordena os elementos</span>

In [37]:
# Array unidimensional
array = np.array([3, 1, 5, 2, 4])

# Ordenando o array
array_ordenado = np.sort(array)

# Apresenta os arrays
print("Array original:", array)
print("Array ordenado:", array_ordenado, '\n')

#==============================================================================

# Array unidimensional
array = np.array(["Hoje", "amanhã", "Bom dia", "bom dia"])

# Ordenando o array
array_ordenado = np.sort(array)

# Apresenta os arrays
print("Array original:", array)
print("Array ordenado:", array_ordenado)

Array original: [3 1 5 2 4]
Array ordenado: [1 2 3 4 5] 

Array original: ['Hoje' 'amanhã' 'Bom dia' 'bom dia']
Array ordenado: ['Bom dia' 'Hoje' 'amanhã' 'bom dia']


In [35]:
# Array bidimensional
array = np.array([[3, 1, 5], [2, 4, 6], [7, 0, 9]])

# Ordenando cada linha do array
array_ordenado = np.sort(array, axis=1)

# Apresenta os arrays
print("Array original:\n", array, '\n')
print("Array ordenado por linha:\n", array_ordenado)

Array original:
 [[3 1 5]
 [2 4 6]
 [7 0 9]] 

Array ordenado por linha:
 [[1 3 5]
 [2 4 6]
 [0 7 9]]


In [34]:
# Array bidimensional
array = np.array([[3, 1, 5], [2, 4, 6], [7, 0, 9]])

# Ordenando cada coluna do array
array_ordenado = np.sort(array, axis=0)

# Apresenta os arrays
print("Array original:\n", array, '\n')
print("Array ordenado por coluna:\n", array_ordenado)

Array original:
 [[3 1 5]
 [2 4 6]
 [7 0 9]] 

Array ordenado por coluna:
 [[2 0 5]
 [3 1 6]
 [7 4 9]]


<span style="color: #FFC107; font-size: 22px;">**np.dot()**</span>

<span style="color: #FFC107; font-size: 18px;">Calcula o produto escalar de duas matrizes</span>

In [38]:
# Vetor que representa a quantidade de itens vendidos
quantidade = np.array([10, 2, 6, 9])

# Vetor que representa o preço unitário de cada item
preco_unitario = np.array([2, 1, 2, 2])

# Calcula o ganho de cada item
preco_quantidade = quantidade * preco_unitario

# Calcula o ganho total
soma_preco_quantidade = np.sum(preco_quantidade)

# Apresenta o ganho total
print(soma_preco_quantidade)

#=========================================================================================

# Calcula o produto escalar de dois vetores
soma_preco_quantidade = np.dot(quantidade, preco_unitario)

# Apresenta o ganho total
print(soma_preco_quantidade)

52
52


In [44]:
# Duas matrizes
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])

# Produto de matrizes
produto_matrizes = np.dot(matriz1, matriz2)

# Apresenta as matrizes
print('Matriz 1:\n', matriz1, '\n')
print('Matriz 2:\n', matriz2, '\n')
print("Produto das matrizes:\n", produto_matrizes)

Matriz 1:
 [[1 2]
 [3 4]] 

Matriz 2:
 [[5 6]
 [7 8]] 

Produto das matrizes:
 [[19 22]
 [43 50]]


In [96]:
# Cria uma instância da classe 'default_rng()'
rng = np.random.default_rng()

# Gera um número aleatório e flutuante entre 0 e 1
numero_aleatorio_1 = rng.random()
print(numero_aleatorio_1, '\n')

# Gera 5 números aleatórios e flutuantes entre 0 e 100
numero_aleatorio_2 = rng.random(5) * 100
print(numero_aleatorio_2, '\n')

# Gera 20 números aleatórios inteiros entre 1 e 7
numero_aleatorio_3 = rng.integers(low = 1, high = 101, size = 20)
print(numero_aleatorio_3, '\n')

0.2638778466646875 

[87.18689035 38.82067778 17.51187463 15.80738718 20.43146287] 

[43 33  2 53 77 15 47 79 10 60 53 37 27 67 90  3 91 37 77 52] 



In [117]:
# Cria uma instância da classe 'default_rng()'
# Qualquer pessoa que usar a mesma 'seed' que esta, terá os mesmos resultados
rng = np.random.default_rng(seed = 42)

# Gera um número aleatório e flutuante entre 0 e 1
numero_aleatorio_1 = rng.random()
print(numero_aleatorio_1, '\n')

# Gera 5 números aleatórios e flutuantes entre 0 e 100
numero_aleatorio_2 = rng.random(5) * 100
print(numero_aleatorio_2, '\n')

# Gera 20 números aleatórios inteiros entre 1 e 7
numero_aleatorio_3 = rng.integers(low = 1, high = 101, size = 20)
print(numero_aleatorio_3, '\n')

# Apresenta a posição do maior elemento do array
posicao_max = np.argmax(numero_aleatorio_3)
print('O maior elemento está na posição: ', posicao_max, '\n')

# Apresenta a posição do menor elemento do array
posicao_min = np.argmin(numero_aleatorio_3)
print('O menor elemento está na posição: ', posicao_min)

0.7739560485559633 

[43.88784398 85.85979199 69.73680291  9.41773479 97.56223516] 

[74 77 72 79 52 13 84 46 51 38 19 93 79 65 41 83 55 45 46 23] 

O maior elemento está na posição:  11 

O menor elemento está na posição:  5


In [137]:
numero_aleatorio_4 = rng.integers(low = 100, high = 501, size = 100)
print(numero_aleatorio_4, '\n')

mediana = np.median(numero_aleatorio_4)
print('Mediana: ', mediana, '\n')

n_percentil = 1
percentil = np.percentile(numero_aleatorio_4, n_percentil)
print(f'{n_percentil}% dos elementos são menores ou iguais à: ', percentil, '\n')

desvio_padrao = np.std(numero_aleatorio_4)
print('Desvio padrão: ', desvio_padrao, '\n')

variancia = np.var(numero_aleatorio_4)
print('Variância: ', variancia)

[257 421 253 119 464 194 140 349 193 444 277 101 481 306 205 371 312 111
 404 260 380 459 344 369 202 195 266 441 310 239 412 442 461 219 384 336
 280 259 145 210 320 455 447 175 372 134 370 237 280 387 270 423 313 500
 355 218 410 263 314 154 147 330 174 500 443 381 394 338 124 257 298 467
 188 299 237 153 141 246 133 126 240 180 322 107 221 281 486 354 453 237
 280 268 455 484 485 401 301 316 493 214] 

Mediana:  300.0 

1% dos elementos são menores ou iguais à:  106.94 

Desvio padrão:  112.5178403632064 

Variância:  12660.2644


In [57]:
rng = np.random.default_rng()

numero_aleatorio_4 = rng.integers(low = 100, high = 200, size = (3, 5))
print(numero_aleatorio_4, '\n')

[[136 163 154 143 104]
 [128 160 141 106 142]
 [131 178 133 126 159]] 



In [65]:
rng = np.random.default_rng()

numero_aleatorio_4 = rng.integers(low = 1, high = 101, size = (3, 5, 4))
print(numero_aleatorio_4, '\n')

[[[95  9 46 94]
  [95  6 67 22]
  [14 85 94 40]
  [ 6 24 41 59]
  [74 86 31 86]]

 [[ 4 81 12 57]
  [61 63 22 89]
  [18 35 49 59]
  [55 37 66 73]
  [98 48  6 28]]

 [[73 92 34  6]
  [14 28 95 28]
  [10 52 82 65]
  [82 77 33 31]
  [97 14 71 45]]] 



<span style="color: #FFC107; font-size: 22px;">**np.where()**</span> <br>

In [37]:
# Define uma seed para valores aleatórios
aleatorio = np.random.default_rng(seed = 42)

# Define um conjunto de valores aleatórios
salarios = aleatorio.integers(low = 500, high = 6000, size = 5)
print('Salários: ', salarios, '\n')

# Apresenta a média salarial
media_salarial = np.mean(salarios)
print('Média salarial: ', media_salarial, '\n')

salarios_acima_media_1 = np.where(salarios > media_salarial)
print(f'Posição no array dos salários acima de {media_salarial}: ', salarios_acima_media_1[0], '\n')

print(f'Valor dos salários acima de {media_salarial}: ', salarios[salarios_acima_media_1], '\n')

salarios_acima_media_2 = salarios[salarios > media_salarial]
print(salarios_acima_media_2)

Salários:  [ 990 4756 4100 2913 2881] 

Média salarial:  3128.0 

Posição no array dos salários acima de 3128.0:  [1 2] 

Valor dos salários acima de 3128.0:  [4756 4100] 

[4756 4100]


In [44]:
# Define uma seed para valores aleatórios
aleatorio = np.random.default_rng(seed = 42)

# Define um conjunto de valores aleatórios
salarios = aleatorio.integers(low = 500, high = 6000, size = 5)
print('Salários: ', salarios, '\n')

salarios_modificado = np.where(salarios >= media_salarial, True, 'Salários pequenos')
print(salarios_modificado, '\n')

salarios_modificado = np.where(salarios >= media_salarial, salarios * 1.1, salarios)
print(salarios_modificado)

Salários:  [ 990 4756 4100 2913 2881] 

['Salários pequenos' 'True' 'True' 'Salários pequenos' 'Salários pequenos'] 

[ 990.  5231.6 4510.  2913.  2881. ]


In [48]:
np.where((salarios >= 2900) & (salarios <= 5000))

salarios[(salarios >= 2900) & (salarios <= 5000)]

np.where((salarios >= 2900) & (salarios <= 5000), True, 'oi')

array(['oi', 'True', 'True', 'True', 'oi'], dtype='<U5')

In [52]:
np.where((salarios <= 2900) | (salarios >= 5000))

salarios[(salarios <= 2900) | (salarios >= 5000)]

np.where((salarios <= 2900) | (salarios >= 5000), True, 'oi')

array(['True', 'oi', 'oi', 'oi', 'True'], dtype='<U5')

In [41]:
# Define uma instância para a geração de números aleatórios
aleatorio = np.random.default_rng(seed = 12)

# Cria um array com valores aleatórios e inteiros
valores = aleatorio.integers(low = 100, high = 501, size = 14)
print(valores, '\n')

# Apresenta a quantidade de dimensões do vetor/matriz
qtd_dimensoes = valores.ndim
print('A quantidade de dimensões é: ', qtd_dimensoes, '\n')

# Apresenta o formato
formato = valores.shape
print('O formato do vetor/matriz é: ', formato)

[345 200 490 479 125 175 179 171 333 240 293 192 481 368] 

A quantidade de dimensões é:  1 

O formato do vetor/matriz é:  (14,)


In [90]:
valores_reshaped_1 = np.reshape(valores, (2, 7))
print(valores_reshaped_1, '\n')

valores_reshaped_2 = valores.reshape(2, 7)
print(valores_reshaped_2, '\n')

# o '-1' serve para completar o formato
valores_reshaped_3 = np.reshape(valores, (2, -1))
print(valores_reshaped_3, '\n')

# Apresenta a quantidade de dimensões do vetor/matriz
qtd_dimensoes = valores_reshaped_2.ndim
print('A quantidade de dimensões é: ', qtd_dimensoes, '\n')

# Apresenta o formato
formato = valores_reshaped_2.shape
print('O formato do vetor/matriz é: ', formato)

[[345 200 490 479 125 175 179]
 [171 333 240 293 192 481 368]] 

[[345 200 490 479 125 175 179]
 [171 333 240 293 192 481 368]] 

[[345 200 490 479 125 175 179]
 [171 333 240 293 192 481 368]] 

A quantidade de dimensões é:  2 

O formato do vetor/matriz é:  (2, 7)


In [50]:
soma_colunas = valores_reshaped_2.sum(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.sum(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [516 533 730 772 317 656 547] 

Soma das linhas:  [1993 2078]


In [51]:
soma_colunas = valores_reshaped_2.mean(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.mean(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [258.  266.5 365.  386.  158.5 328.  273.5] 

Soma das linhas:  [284.71428571 296.85714286]


In [52]:
soma_colunas = valores_reshaped_2.max(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.max(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [345 333 490 479 192 481 368] 

Soma das linhas:  [490 481]


In [53]:
soma_colunas = valores_reshaped_2.min(axis = 0)
print('Soma das colunas: ', soma_colunas, '\n')

soma_linhas = valores_reshaped_2.min(axis = 1)
print('Soma das linhas: ', soma_linhas)

Soma das colunas:  [171 200 240 293 125 175 179] 

Soma das linhas:  [125 171]


<span style="color: #FFC107; font-size: 22px;">**np.arange()**</span>

In [72]:
a = np.arange(15)
print(a, '\n')

b = np.arange(8, 22)
print(b, '\n')

c = np.arange(5, 15, 0.3)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 

[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21] 

[ 5.   5.3  5.6  5.9  6.2  6.5  6.8  7.1  7.4  7.7  8.   8.3  8.6  8.9
  9.2  9.5  9.8 10.1 10.4 10.7 11.  11.3 11.6 11.9 12.2 12.5 12.8 13.1
 13.4 13.7 14.  14.3 14.6 14.9]


<span style="color: #FFC107; font-size: 22px;">**np.linspace()**</span>

In [99]:
a = np.linspace(0,8,3)
print(a, '\n')

tamanho_a = a.size
print('Tamanho: ', tamanho_a, '\n', '-' * 80)

b = np.linspace(0,8,10)
print(b, '\n')

tamanho_b = b.size
print('Tamanho: ', tamanho_b, '\n', '-' * 80)

c = np.linspace(0,8,30)
print(c, '\n')

tamanho_c = c.size
print('Tamanho: ', tamanho_c, '\n')

[0. 4. 8.] 

Tamanho:  3 
 --------------------------------------------------------------------------------
[0.         0.88888889 1.77777778 2.66666667 3.55555556 4.44444444
 5.33333333 6.22222222 7.11111111 8.        ] 

Tamanho:  10 
 --------------------------------------------------------------------------------
[0.         0.27586207 0.55172414 0.82758621 1.10344828 1.37931034
 1.65517241 1.93103448 2.20689655 2.48275862 2.75862069 3.03448276
 3.31034483 3.5862069  3.86206897 4.13793103 4.4137931  4.68965517
 4.96551724 5.24137931 5.51724138 5.79310345 6.06896552 6.34482759
 6.62068966 6.89655172 7.17241379 7.44827586 7.72413793 8.        ] 

Tamanho:  30 



In [92]:
a.size

3

In [ ]:
A = np.array([[0,1,2],[3,4,5]])
print(A)
print('')
print(A.shape)

[[0 1 2]
 [3 4 5]]

(2, 3)


In [ ]:
B = np.array([1,2,3])
print(B)
print('')
print(b.shape)

[1 2 3]

(3,)


In [ ]:
np.matmul(A, B)

array([ 8, 26])

O seu funcionamento é

(n,k),(k,m) $\rightarrow$ (n,m)

Sabendo que:
* A = (2,3) 
* B = (3, 1)

Logo:
* n = 2
* k = 3
* m = 1

Com isso:
* (<span style = 'color: blue'>2</span>,**3**),(**3**,<span style = 'color: red'>1</span>) $\rightarrow$ (<span style = 'color: blue'>2</span>,<span style = 'color: red'>1</span>)

Fazendo o produto matricial da matriz, obtêm-se:

1. 
  \begin{vmatrix} 
  0(1) + 1(2) + 2(3) & 3(1) + 4(2) + 5(3)\\ 
  \end{vmatrix}

2. 
  \begin{vmatrix} 
  0 + 2 + 6 & 3 + 8 + 15\\ 
  \end{vmatrix}

3. 
  \begin{vmatrix} 
  8 & 26\\ 
  \end{vmatrix}

### A forma curta de np.matmul(x1, x2) e x1 @ x2

In [ ]:
A @ B

array([ 8, 26])

In [ ]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)