<span style="color: #FFC107; font-size: 22px;">Referências</span>

1. [Documentação do Numpy](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html)

<span style="color: #FFC107; font-size: 22px;">Importação das bibliotecas</span>

In [10]:
import numpy as np
import time

<span style="color: #FFC107; font-size: 18px;">No Numpy, todos os elementos de um `array` são do mesmo tipo.</span>

<span style="color: #FFC107; font-size: 18px;">Caso inicialmente eles sejam de tipos diferentes, o numpy altera para o formato mais genérico.</span>

In [9]:
# Definindo os elementos da lista
lista_elementos = [24, "Bom dia", 3.7]

# Percorrendo todos os elementos da lista
for elemento in lista_elementos:

    # Apresentando o tipo do elemento
    print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos do array
np_lista = np.array(lista_elementos)

# Percorrendo todos os elementos do array
for elemento in np_lista:

    # Apresentando o tipo do elemento
    print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos da lista
lista_elementos = [24, 2.5 , 9, 3.7]

# Percorrendo todos os elementos da lista
for elemento in lista_elementos:

    # Apresentando o tipo do elemento
    print(type(elemento))

# Pulando uma linha
print('')

#==========================================================================

# Definindo os elementos do array
np_lista = np.array(lista_elementos)

# Percorrendo todos os elementos do array
for elemento in np_lista:

    # Apresentando o tipo do elemento
    print(type(elemento))

<class 'int'>
<class 'str'>
<class 'float'>

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

<class 'int'>
<class 'float'>
<class 'int'>
<class 'float'>

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


<span style="color: #FFC107; font-size: 18px;">Na lista não é possível somar um número qualquer de forma direta.</span>

<span style="color: #FFC107; font-size: 18px;">Já em um array do Numpy isso é possível.</span>

In [20]:
# Cria uma lista de números
lista_numeros = [1, 2, 3, 4]

# Acrescenta o número 1 a lista
lista_numeros = lista_numeros + [1]

# Apresenta a lista de números com o acréscimo do número 2
print(lista_numeros)

#=====================================================================

# Cria um array
np_numeros = np.array(lista_numeros)

# Soma o número 1 ao array
np_numeros = np_numeros + 1

# Apresenta a soma do número 1 ao array
print(np_numeros)

[1, 2, 3, 4, 1]
[2 3 4 5 2]


In [24]:
# Lista com números de 1 à 10.000.000
lista = list(range(1, 10_000_000))

# Tempo inicial
inicio_lista = time.time()

# Calcula todos os elementos da lista
soma_lista = sum(lista)

# Tempo final
fim_lista = time.time()

# Calcula o tempo necessário para calcular os elementos da lista
duracao = fim_lista - inicio_lista

# Apresenta a duração para somar todos os números da lista
print(f'O tempo total para somar os elementos da lista foi de: {duracao} segundos')

#================================================================================================

# Array com números de 1 à 10.000.000
array = np.array(range(1, 10_000_000))

# Tempo inicial
inicio_np = time.time()

# Calcula todos os elementos da lista
soma_lista = np.sum(array)

# Tempo final
fim_np = time.time()

# Calcula o tempo necessário para calcular os elementos da lista
duracao = fim_np - inicio_np

# Apresenta a duração para somar todos os números do array
print(f'O tempo total para somar os elementos do array foi de: {duracao} segundos')

O tempo total para somar os elementos da lista foi de: 0.1981029510498047 segundos
O tempo total para somar os elementos do array foi de: 0.003912687301635742 segundos


In [ ]:
A = np.array([[0,1,2],[3,4,5]])
print(A)
print('')
print(A.shape)

[[0 1 2]
 [3 4 5]]

(2, 3)


In [ ]:
B = np.array([1,2,3])
print(B)
print('')
print(b.shape)

[1 2 3]

(3,)


In [ ]:
np.matmul(A, B)

array([ 8, 26])

O seu funcionamento é

(n,k),(k,m) $\rightarrow$ (n,m)

Sabendo que:
* A = (2,3) 
* B = (3, 1)

Logo:
* n = 2
* k = 3
* m = 1

Com isso:
* (<span style = 'color: blue'>2</span>,**3**),(**3**,<span style = 'color: red'>1</span>) $\rightarrow$ (<span style = 'color: blue'>2</span>,<span style = 'color: red'>1</span>)

Fazendo o produto matricial da matriz, obtêm-se:

1. 
  \begin{vmatrix} 
  0(1) + 1(2) + 2(3) & 3(1) + 4(2) + 5(3)\\ 
  \end{vmatrix}

2. 
  \begin{vmatrix} 
  0 + 2 + 6 & 3 + 8 + 15\\ 
  \end{vmatrix}

3. 
  \begin{vmatrix} 
  8 & 26\\ 
  \end{vmatrix}

### A forma curta de np.matmul(x1, x2) e x1 @ x2

In [ ]:
A @ B

array([ 8, 26])

In [ ]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)