In [83]:
import numpy as np
from datetime import datetime

In [162]:
np.random.seed(1)

vetor_1 = np.random.randint(1, 21, 7)
print(vetor_1, '\n')

total_linha = np.sum(a = vetor_1)
print(total_linha)

[ 6 12 13  9 10 12  6] 

68


In [121]:
np.random.seed(1)

vetor_1 = np.random.randint(1, 21, (3, 7))
print(vetor_1, '\n')

total_linha = np.sum(a = vetor_1, axis = 1, keepdims = True)
print(total_linha, '\n')

total_coluna = np.sum(a = vetor_1, axis = 0, keepdims = True)
print(total_coluna)

[[ 6 12 13  9 10 12  6]
 [16  1 17  2 13  8 14]
 [ 7 19  6 19 12 11 15]] 

[[68]
 [71]
 [89]] 

[[29 32 36 30 35 31 35]]


In [188]:
np.random.seed(1)

vetor_1 = np.random.randint(1, 21, (2, 3, 7))
print(vetor_1, '\n')

total_linha = np.sum(a = vetor_1, axis = 0, keepdims = True)
print(total_linha, '\n')

[[[ 6 12 13  9 10 12  6]
  [16  1 17  2 13  8 14]
  [ 7 19  6 19 12 11 15]]

 [[19  5 10 18  1 14 10]
  [10  8  2  1 18  9 14]
  [20 16 11  9  8  4  7]]] 

[[[25 17 23 27 11 26 16]
  [26  9 19  3 31 17 28]
  [27 35 17 28 20 15 22]]] 



In [198]:
total_linha[0][1]

array([26,  9, 19,  3, 31, 17, 28])

In [199]:
np.random.seed(1)

# 7: Os dias da semana
# 3: Os tipos de produto
# 2: Quantidade de funcionários
# 4: Empresas
vetor_4 = np.random.randint(1, 21, (4, 2, 3, 7))
print(vetor_4, '\n')

[[[[ 6 12 13  9 10 12  6]
   [16  1 17  2 13  8 14]
   [ 7 19  6 19 12 11 15]]

  [[19  5 10 18  1 14 10]
   [10  8  2  1 18  9 14]
   [20 16 11  9  8  4  7]]]


 [[[18  4  5 18 12 13 17]
   [14 20 10 19 16  1  5]
   [16  3  8  9 10  4  8]]

  [[ 5  6 20  7  9  1  3]
   [11 16 16  8 20 11 15]
   [ 1  2 18 14  4  1 14]]]


 [[[ 7  7  3 13 12  8 14]
   [ 9 12 13 12  5  8  8]
   [14  5 17 19  1 14 11]]

  [[18  8 11  1 13  2 10]
   [19 20  2  3 13  8  3]
   [11  1 10 19  7  3  8]]]


 [[[ 8 17 16  6 18 11 17]
   [ 6 14 18 19  2 11  1]
   [ 8  1 20 18 15 14 12]]

  [[ 7 14 16 10  3  8  6]
   [ 5  6  9 14 18 18 16]
   [14  9 15 14 17 11 14]]]] 



In [202]:
# Dados da empresa 1
vetor_4[2]

array([[[ 7,  7,  3, 13, 12,  8, 14],
        [ 9, 12, 13, 12,  5,  8,  8],
        [14,  5, 17, 19,  1, 14, 11]],

       [[18,  8, 11,  1, 13,  2, 10],
        [19, 20,  2,  3, 13,  8,  3],
        [11,  1, 10, 19,  7,  3,  8]]])

In [ ]:
# Dados da empresa 1
# Dados do funcionário 1
vetor_4[0][0]

array([[ 6, 12, 13,  9, 10, 12,  6],
       [16,  1, 17,  2, 13,  8, 14],
       [ 7, 19,  6, 19, 12, 11, 15]])

In [ ]:
# Dados da empresa 1
# Dados do funcionário 1
# Dados do produto 1
vetor_4[0][0][0]

array([ 6, 12, 13,  9, 10, 12,  6])

In [ ]:
# Dados da empresa 1
# Dados do funcionário 1
# Dados do produto 1
# Dados do primeiro dia da semana
vetor_4[0][0][0][0]

6

In [187]:
total_linha = np.sum(a = vetor_4, axis = 0, keepdims = True)
print(total_linha, '\n')

[[[[39 40 37 46 52 44 54]
   [45 47 58 52 36 28 28]
   [45 28 51 65 38 43 46]]

  [[49 33 57 36 26 25 29]
   [45 50 29 26 69 46 48]
   [46 28 54 56 36 19 43]]]] 



In [151]:
a = np.array([2, 4, 3])
a = a.reshape(1,-1)
at = a.T

print(a)
print('Vetor =>', a.shape, '\n')

print(at)
print('Vetor =>', at.shape)

[[2 4 3]]
Vetor => (1, 3) 

[[2]
 [4]
 [3]]
Vetor => (3, 1)


In [142]:
at @ a

array([[ 4,  8,  6],
       [ 8, 16, 12],
       [ 6, 12,  9]])

In [143]:
a @ at

array([[29]])

In [3]:
# Exemplo 1: Unindo duas listas
lista1 = [1, 2, 3]
lista2 = ['a', 'b', 'c']
zipado = zip(lista1, lista2)
print(list(zipado))  # [(1, 'a'), (2, 'b'), (3, 'c')]

[(1, 'a'), (2, 'b'), (3, 'c')]


In [4]:
# Exemplo 2: Unindo listas de tamanhos diferentes
lista3 = [1, 2, 3, 4]
lista4 = ['a', 'b']
zipado_dif = zip(lista3, lista4)
print(list(zipado_dif))  # [(1, 'a'), (2, 'b')]

[(1, 'a'), (2, 'b')]


In [5]:
# Exemplo 3: Descompactando com zip
zipado = zip(lista1, lista2)
lista1_unzip, lista2_unzip = zip(*zipado)
print(lista1_unzip)  # (1, 2, 3)
print(lista2_unzip)  # ('a', 'b', 'c')

(1, 2, 3)
('a', 'b', 'c')


In [6]:
# Exemplo 4: Iterando sobre múltiplas listas simultaneamente
for num, letra in zip(lista1, lista2):
    print(f'Número: {num}, Letra: {letra}')
# Número: 1, Letra: a
# Número: 2, Letra: b
# Número: 3, Letra: c

Número: 1, Letra: a
Número: 2, Letra: b
Número: 3, Letra: c


In [7]:
# Exemplo 5: Usando zip com dicionários
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
zip_dict = zip(dict1.items(), dict2.items())
print(list(zip_dict))  # [(('a', 1), ('c', 3)), (('b', 2), ('d', 4))]

[(('a', 1), ('c', 3)), (('b', 2), ('d', 4))]


In [9]:
# Exemplo 6: Usando zip com diferentes tipos de iteráveis
lista1 = [1, 2, 3]
tupla = (10, 20, 30)
conjunto = {'x', 'y', 'z'}
zip_mixed = zip(lista1, tupla, conjunto)
print(list(zip_mixed))  # [(1, 10, 'x'), (2, 20, 'y'), (3, 30, 'z')]

[(1, 10, 'z'), (2, 20, 'x'), (3, 30, 'y')]


In [13]:
conjunto = {'x', 'y', 'z', 'z'}
len(conjunto)

3