In [3]:
# Exemplo 1: Unindo duas listas
lista1 = [1, 2, 3]
lista2 = ['a', 'b', 'c']
zipado = zip(lista1, lista2)
print(list(zipado))  # [(1, 'a'), (2, 'b'), (3, 'c')]

[(1, 'a'), (2, 'b'), (3, 'c')]


In [4]:
# Exemplo 2: Unindo listas de tamanhos diferentes
lista3 = [1, 2, 3, 4]
lista4 = ['a', 'b']
zipado_dif = zip(lista3, lista4)
print(list(zipado_dif))  # [(1, 'a'), (2, 'b')]

[(1, 'a'), (2, 'b')]


In [5]:
# Exemplo 3: Descompactando com zip
zipado = zip(lista1, lista2)
lista1_unzip, lista2_unzip = zip(*zipado)
print(lista1_unzip)  # (1, 2, 3)
print(lista2_unzip)  # ('a', 'b', 'c')

(1, 2, 3)
('a', 'b', 'c')


In [6]:
# Exemplo 4: Iterando sobre múltiplas listas simultaneamente
for num, letra in zip(lista1, lista2):
    print(f'Número: {num}, Letra: {letra}')
# Número: 1, Letra: a
# Número: 2, Letra: b
# Número: 3, Letra: c

Número: 1, Letra: a
Número: 2, Letra: b
Número: 3, Letra: c


In [7]:
# Exemplo 5: Usando zip com dicionários
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}
zip_dict = zip(dict1.items(), dict2.items())
print(list(zip_dict))  # [(('a', 1), ('c', 3)), (('b', 2), ('d', 4))]

[(('a', 1), ('c', 3)), (('b', 2), ('d', 4))]


In [9]:
# Exemplo 6: Usando zip com diferentes tipos de iteráveis
lista1 = [1, 2, 3]
tupla = (10, 20, 30)
conjunto = {'x', 'y', 'z'}
zip_mixed = zip(lista1, tupla, conjunto)
print(list(zip_mixed))  # [(1, 10, 'x'), (2, 20, 'y'), (3, 30, 'z')]

[(1, 10, 'z'), (2, 20, 'x'), (3, 30, 'y')]


___

In [13]:
conjunto = {'x', 'y', 'z', 'z'}
len(conjunto)

3

___

In [7]:
from functools import reduce

# Exemplo 1: Função lambda simples
# Uma função lambda que soma dois números
soma = lambda x, y: x + y
print(soma(5, 3))  # Saída: 8

8


In [5]:
# Exemplo 2: Função lambda com map
# Usando lambda para elevar ao quadrado cada elemento de uma lista
lista = [1, 2, 3, 4, 5]
quadrados = list(map(lambda x: x ** 2, lista))
print(quadrados)  # Saída: [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


In [6]:
# Exemplo 3: Função lambda com filter
# Usando lambda para filtrar números pares de uma lista
pares = list(filter(lambda x: x % 2 == 0, lista))
print(pares)  # Saída: [2, 4]

[2, 4]


In [11]:
# Exemplo 4: Função lambda com reduce
# Usando lambda para calcular o produto de todos os elementos de uma lista
produto = reduce(lambda x, y: x * y, lista)
print(produto)  # Saída: 120

120


In [ ]:
# Exemplo 5: Função lambda com sorted
# Usando lambda para ordenar uma lista de tuplas pelo segundo elemento
tuplas = [(1, 2), (3, 1), (5, 4), (2, 3)]
ordenado = sorted(tuplas, key=lambda x: x[1])
print(ordenado)  # Saída: [(3, 1), (1, 2), (2, 3), (5, 4)]

# Exemplo 6: Função lambda com zip
# Usando lambda para somar elementos de duas listas
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
soma_listas = list(map(lambda x, y: x + y, lista1, lista2))
print(soma_listas)  # Saída: [5, 7, 9]

# Exemplo 7: Função lambda com list comprehension
# Usando lambda dentro de uma list comprehension para transformar elementos
transformada = [(lambda x: x * 2)(x) for x in lista]
print(transformada)  # Saída: [2, 4, 6, 8, 10]

# Exemplo 8: Função lambda com dicionários
# Usando lambda para ordenar um dicionário por seus valores
dicionario = {'a': 3, 'b': 1, 'c': 2}
ordenado_por_valor = dict(sorted(dicionario.items(), key=lambda item: item[1]))
print(ordenado_por_valor)  # Saída: {'b': 1, 'c': 2, 'a': 3}

___

In [1]:
import numpy as np

In [188]:
rng = np.random.default_rng(seed = 3)

aleatorio = rng.integers(low = 0, high = 101, size = 100)
print(aleatorio, '\n')

mediana = np.median(a = aleatorio, axis = None)
print('Mediana: ', mediana, '\n')

valor = 2
percentil = np.percentile(a = aleatorio, q = valor, axis = None)
print(f'{percentil}% dos elementos são menores ou iguais à: ', valor, '\n')

desvio_padrao = np.std(aleatorio)
print('Desvio padrão: ', desvio_padrao, '\n')

variancia = np.var(aleatorio)
print('Variância: ', variancia)

[81  8 18 23 18 80 87 58  3  9 33 43 62 48 26 16 69 74  3 11 45 39 89 52
 42 43 67 59 17 74 76 96 79 28 32 65 65 70 87 29 94  0  7 98 95 30 14 31
  4 90 66 59 24 47 19 78 47  3 25 71 52 37 25  9 61 66 52 94 93 20 61 63
 25 30 49 74 29 72 66 22 39 83 85 66  0 68 22 82 92 43 96 76 32 88 38 10
 59 85 66 39] 

Mediana:  50.5 

2.94% dos elementos são menores ou iguais à:  2 

Desvio padrão:  28.371244244833534 

Variância:  804.9274999999999


In [185]:
np.percentile(a = aleatorio, q = 3)

3.0

In [189]:
vetor = np.random.randint(1, 11, 20)
vetor

array([ 5,  8,  6,  2,  4,  8,  5,  6,  2,  3,  4,  7,  2,  3, 10,  7,  1,
        6,  4,  6])

In [192]:
vetor.reshape(2, -1)

array([[ 5,  8,  6,  2,  4,  8,  5,  6,  2,  3],
       [ 4,  7,  2,  3, 10,  7,  1,  6,  4,  6]])

In [193]:
np.reshape(a = vetor, newshape = (2, -1))

array([[ 5,  8,  6,  2,  4,  8,  5,  6,  2,  3],
       [ 4,  7,  2,  3, 10,  7,  1,  6,  4,  6]])

In [214]:
a = np.linspace(start = 0, stop = 8, num = 3, dtype = np.float64)

a

array([0., 4., 8.])

In [219]:
rng = np.random.default_rng(seed = 2)

matriz = rng.binomial(p = 0.1, n = 5, size = (5, 5))
matriz

array([[0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 2, 1, 0, 0],
       [0, 0, 1, 1, 0]], dtype=int64)

In [222]:
np.zeros(shape = (3, 3), dtype = np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [224]:
np.zeros_like(a = matriz, dtype = np.float64)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [229]:
np.eye(N = 4, M = 4, k=0, dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [231]:
import pandas as pd

dados = {
        "a": rng.integers(1, 101, 6),
        "b": rng.integers(1, 101, 6),
        "c": rng.integers(1, 101, 6),
}

df = pd.DataFrame(dados)

df

a   b   c
0  60  79  49
1  65  60  90
2  46  48  45
3  41  87  62
4  60  22   8
5  52  44  83

In [233]:
df.at[2, "b"] = 0

In [234]:
df

a   b   c
0  60  79  49
1  65  60  90
2  46   0  45
3  41  87  62
4  60  22   8
5  52  44  83