In [ ]:
# Exemplo 5: Função lambda com sorted
# Usando lambda para ordenar uma lista de tuplas pelo segundo elemento
tuplas = [(1, 2), (3, 1), (5, 4), (2, 3)]
ordenado = sorted(tuplas, key=lambda x: x[1])
print(ordenado)  # Saída: [(3, 1), (1, 2), (2, 3), (5, 4)]

# Exemplo 6: Função lambda com zip
# Usando lambda para somar elementos de duas listas
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
soma_listas = list(map(lambda x, y: x + y, lista1, lista2))
print(soma_listas)  # Saída: [5, 7, 9]

# Exemplo 7: Função lambda com list comprehension
# Usando lambda dentro de uma list comprehension para transformar elementos
transformada = [(lambda x: x * 2)(x) for x in lista]
print(transformada)  # Saída: [2, 4, 6, 8, 10]

# Exemplo 8: Função lambda com dicionários
# Usando lambda para ordenar um dicionário por seus valores
dicionario = {'a': 3, 'b': 1, 'c': 2}
ordenado_por_valor = dict(sorted(dicionario.items(), key=lambda item: item[1]))
print(ordenado_por_valor)  # Saída: {'b': 1, 'c': 2, 'a': 3}

___

In [ ]:
# Criando um conjunto
conjunto = {5, 6, 7}
print(conjunto)  # Saída: {5, 6, 7}

# Adicionando elementos a um conjunto
conjunto.add(8)
print(conjunto)  # Saída: {5, 6, 7, 8}

# Removendo elementos de um conjunto
conjunto.remove(6)
print(conjunto)  # Saída: {5, 7, 8}

# Verificando se um elemento está no conjunto
print(5 in conjunto)  # Saída: True
print(6 in conjunto)  # Saída: False

# União de conjuntos
conjunto2 = {1, 2, 3}
uniao = conjunto.union(conjunto2)
print(uniao)  # Saída: {1, 2, 3, 5, 7, 8}

# Interseção de conjuntos
intersecao = conjunto.intersection(conjunto2)
print(intersecao)  # Saída: set()

# Diferença de conjuntos
diferenca = conjunto.difference(conjunto2)
print(diferenca)  # Saída: {5, 7, 8}

# Diferença simétrica de conjuntos
diferenca_simetrica = conjunto.symmetric_difference(conjunto2)
print(diferenca_simetrica)  # Saída: {1, 2, 3, 5, 7, 8}

# Subconjunto e Superconjunto
conjunto3 = {5, 7}
print(conjunto3.issubset(conjunto))  # Saída: True
print(conjunto.issuperset(conjunto3))  # Saída: True

# Conjuntos imutáveis (frozenset)
conjunto_imutavel = frozenset(conjunto)
print(conjunto_imutavel)  # Saída: frozenset({8, 5, 7})

# Convertendo lista para conjunto (removendo duplicatas)
lista_2 = ['elemento', 6, 1, 2, 5, 6, 'aaa']
conjunto_lista = set(lista_2)
print(conjunto_lista)  # Saída: {1, 2, 5, 6, 'elemento', 'aaa'}

# Convertendo tupla para conjunto
tupla = (1, 2)
conjunto_tupla = set(tupla)
print(conjunto_tupla)  # Saída: {1, 2}

conjunto = {'x', 'y', 'z', 'z'}
len(conjunto)

___

In [1]:
import numpy as np
import random
import pandas as pd
import matplotlib.pyplot as plt

In [58]:
# Criando um dicionário
dicionario = {'nome': 'Alice', 'idade': 25, 'cidade': 'São Paulo'}
print(dicionario)  # Saída: {'nome': 'Alice', 'idade': 25, 'cidade': 'São Paulo'}

# Acessando valores
print(dicionario['nome'])  # Saída: Alice

# Adicionando ou atualizando um valor
dicionario['idade'] = 26
print(dicionario)  # Saída: {'nome': 'Alice', 'idade': 26, 'cidade': 'São Paulo'}

# Removendo um item
del dicionario['cidade']
print(dicionario)  # Saída: {'nome': 'Alice', 'idade': 26}

# Usando o método get() para acessar valores
# Retorna None se a chave não existir
print(dicionario.get('cidade'))  # Saída: None

# Verificando se uma chave está no dicionário
print('nome' in dicionario)  # Saída: True
print('cidade' in dicionario)  # Saída: False

# Iterando sobre chaves e valores
for chave, valor in dicionario.items():
    print(f'{chave}: {valor}')
# Saída:
# nome: Alice
# idade: 26

# Obtendo apenas as chaves
print(dicionario.keys())  # Saída: dict_keys(['nome', 'idade'])

# Obtendo apenas os valores
print(dicionario.values())  # Saída: dict_values(['Alice', 26])

# Obtendo apenas os itens (pares chave-valor)
print(dicionario.items())  # Saída: dict_items([('nome', 'Alice'), ('idade', 26)])

# Removendo e retornando um item
idade = dicionario.pop('idade')
print(idade)  # Saída: 26
print(dicionario)  # Saída: {'nome': 'Alice'}

# Limpando o dicionário
dicionario.clear()
print(dicionario)  # Saída: {}

# Mesclando dois dicionários
dicionario1 = {'a': 1, 'b': 2}
dicionario2 = {'b': 3, 'c': 4}
dicionario1.update(dicionario2)
print(dicionario1)  # Saída: {'a': 1, 'b': 3, 'c': 4}

# Criando um dicionário com chaves e valores padrão
chaves = ['x', 'y', 'z']
valores_padrao = 0
novo_dicionario = dict.fromkeys(chaves, valores_padrao)
print(novo_dicionario)  # Saída: {'x': 0, 'y': 0, 'z': 0}

{'nome': 'Alice', 'idade': 25, 'cidade': 'São Paulo'}
Alice
{'nome': 'Alice', 'idade': 26, 'cidade': 'São Paulo'}
{'nome': 'Alice', 'idade': 26}
None
True
False
nome: Alice
idade: 26
dict_keys(['nome', 'idade'])
dict_values(['Alice', 26])
dict_items([('nome', 'Alice'), ('idade', 26)])
26
{'nome': 'Alice'}
{}
{'a': 1, 'b': 3, 'c': 4}
{'x': 0, 'y': 0, 'z': 0}


In [31]:
x = 3

match x:
    case 1:
        print("x é 1")
    case 2:
        print("x é 2")
    case _:
        print("x não é nem 1 nem 2")

x não é nem 1 nem 2


In [4]:
user = {"name": "Alice", "cidade": "Florianopólis", "age": 30}

match user:
    case {"name": name, "age": age} if age >= 18: print(f"{name} é adulto")
        
    case {"name": name, "age": age}: print(f"{name} é menor de idade")

Alice é adulto


In [ ]:
valor = 10

def func1():
    print(valor)

def func2():
    valor = 3
    print(valor)

def func3():
    global valor
    valor = 6

func1() # Mostra 10, por que a função usou a variável global
func2() # Mostra 3, porque dentro da função foi definida uma variável local
print(valor) # Mostra 10, porque a variável local da função 'func2' não altera a variável global

func3() # Altera o valor da variável global e não local
print(valor)

10
3
10
6


___

In [1]:
import pyautogui
import time

In [ ]:
# Movendo o mouse para uma posição específica (x, y)
print("Movendo o mouse para a posição (500, 500)...")
pyautogui.moveTo(500, 500, duration=1)  # Move o mouse em 1 segundo para (500, 500)

# Realizando um clique
print("Realizando um clique na posição atual...")
pyautogui.click()

# Movendo o mouse relativo à posição atual
print("Movendo o mouse 100 pixels para a direita e 50 para baixo...")
pyautogui.move(100, 50, duration=1)

# Realizando um duplo clique
print("Realizando um duplo clique...")
pyautogui.doubleClick()

# Realizando um clique com botão direito
print("Realizando um clique com o botão direito...")
pyautogui.rightClick()

In [9]:
# Obtendo a posição atual do mouse
current_position = pyautogui.position()
print(f"A posição atual do mouse é: {current_position}")

A posição atual do mouse é: Point(x=1698, y=818)


In [5]:
import pyautogui
import time

In [7]:
# Obtendo a posição atual do mouse
current_position = pyautogui.position()
print(f"A posição atual do mouse é: {current_position}")

A posição atual do mouse é: Point(x=1594, y=570)


In [ ]:
tempo = 20

while True:
# for _ in range(2):
    pyautogui.moveTo(269, 553, duration=1)  # Move o mouse em 1 segundo para (500, 500)
    time.sleep(tempo)
    pyautogui.moveTo(1594, 570, duration=1)  # Move o mouse em 1 segundo para (500, 500)
    time.sleep(tempo)

___

In [5]:
import time
import numpy as np

In [26]:
vetor_1 = np.random.randint(low = 0, high = 6, size = 3)
vetor_2 = np.random.randint(low = 0, high = 6, size = 3)
print(vetor_1)
print(vetor_2)

[2 5 4]
[0 1 3]


In [27]:
vetor_1 @ vetor_2

np.int32(17)

In [28]:
np.dot(a = vetor_1, b = vetor_2)

np.int32(17)

In [29]:
np.matmul(vetor_1, vetor_2)

np.int32(17)

In [ ]:
!pip install -u pandas

In [22]:
vetor[(vetor > 10) & (vetor < 15)]

array([12, 12, 14, 12], dtype=int32)

In [20]:
vetor[[0, 1]]

array([3, 0], dtype=int32)